### ISSUE TITLE
How to get the date_start and date_stop of when the interactions happened

### ISSUE THREAD

**Issue by lucasdedavid** [daroczig/fbRads#101]
Hi. I want to collect Fb Ads data regarding ads performance and filter by the day that the actions happened. When i'm pulling data by date_preset (last 90 days) all the date_start and date_stop are the same. Is there a way to get date right?

**Comment by daroczig** [comment]
I think you are looking for `time_increment` @ https://developers.facebook.com/docs/marketing-api/insights/parameters

**Comment by lucasdedavid** [comment]
That is it! Thank you.
