### ISSUE TITLE
Using Filters

### ISSUE THREAD

**Issue by TejPandya1** [daroczig/fbRads#102]
Hello Daroczig

Can you provide me with the sample code of how to use filters in fbinsights

**Comment by daroczig** [comment]
This is not really specific to `fbRads`: https://developers.facebook.com/docs/marketing-api/insights/parameters

**Comment by TejPandya1** [comment]
I need that as a help i have read api document but i am not able to use
filters successfully

Your help will be appreciated

**Comment by daroczig** [comment]
^^ see above commit closing this ticket

**Comment by TejPandya1** [comment]
Please help me with the sample code as i used filtering but it is showing
syntax error

**Comment by daroczig** [comment]
I've provided sample code in the above-mentioned commit.
