### ISSUE TITLE
ZIP code for reach estimate

### ISSUE THREAD

**Issue by devmag** [daroczig/fbRads#104]
Hello -- I am trying to get the zip code specific reach estimates -- is there a minimum working example for how to encode this in the targeting_specs?

Especially if you want to have multiple zip codes comprised as a single area -- e.g. US:60615 AND US:60637 as one big target area combined.

This would be tremendously helpful also for the documentation!

**Comment by daroczig** [comment]
Sorry, I cannot help with these kinds of requests -- your question is not specific to the R implementation, but you are asking about the FB Marketing API itself. See, especially the JSON examples in the curl requests at https://developers.facebook.com/docs/marketing-api/targeting-specs
