### ISSUE TITLE
fbad_add_audience error

### ISSUE THREAD

**Issue by bcastane** [daroczig/fbRads#106]
Hi,
I am trying to create an audience using fbad_add_audience error, but appears an error mesage saying:
`Error in fbad_request(fbacc, path = paste0("act_", fbacc$account_id, "/customaudiences"),  : 
  (#100) Missing parameter(s): customer_file_source`

The line that i am using is:
`aud_id <- fbad_create_audience(fbacc,name = "TEST 1234 R",description = "TEST R R",subtype = "CUSTOM")`

I tried to give it through the "opt_out_link" parameter... but with no success.

Thanks

**Comment by bcastane** [comment]
I still have the same issue. Did someone solve it? or created a work around?
Regards,

**Comment by daroczig** [comment]
@bcastane I've just pushed an update where you can pass arbitrary params to the FB API -- that will hopefully resolve your issue. Please let me know if it works.

**Comment by bcastane** [comment]
Thanks! is working!

**Comment by AndreGrow** [comment]
I have the same problem. Could you share the code of the solution? Thanks in advance!

**Comment by Hamza012** [comment]
I write this code
`fs.createReadStream('Book1.csv')
            .pipe(csv())
            .on('data', (data) => {
                //   results.push(data)
                fields = [
                ];
                params = {
                    'name': adSetName,
                    'start_time': start_time,
                    'end_time': end_time,
                    // 'campaign_id': campaign,
                    'customer_file_source': data,
                };
            })
await account.createCustomAudience(
            fields,
            params
        );`
but not working
