### ISSUE TITLE
fbad_list

### ISSUE THREAD

**Issue by scottyha** [daroczig/fbRads#11]
Hi there,

Apologies, as I'm a new in R. I can't get any fb list item to work. eg:

> fbRads::fbad_list_ad(fbacc, id, statuses = "ACTIVE", fields = "id")
> ERROR [2016-03-11 00:19:19] URL:  https://graph.facebook.com/v2.5/
> ERROR [2016-03-11 00:19:19] Method:  GET
> ERROR [2016-03-11 00:19:19] Params:  List of 3
>  $ fields          : chr "id"
>  $ limit           : num 1000
>  $ effective_status:Class 'json'  chr "[\"ACTIVE\"]"
> ERROR [2016-03-11 00:19:19] Header: {"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api\""],"Access-Control-Allow-Origin":["*"],"Content-Type":["application/json; charset=UTF-8"],"X-FB-Trace-ID":["HlKEAU9mYcx"],"X-FB-Rev":["2223643"],"Pragma":["no-cache"],"Cache-Control":["no-store"],"Facebook-API-Version":["v2.5"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"Vary":["Accept-Encoding"],"X-FB-Debug":["V/TZQWM169EvKsuhl2KHgIXhWCQMiQ4Vv/XRsJUa2/twEoA6aeoEk4JcMi3uW8Q/C1C/uOu/nnGAPOR9ZLn5aQ=="],"Date":["Thu, 10 Mar 2016 13:19:18 GMT"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"status":["400"],"statusMessage":["Bad Request"]}
> ERROR [2016-03-11 00:19:19] Body: {"error":{"message":"Unsupported get request. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100,"fbtrace_id":"HlKEAU9mYcx"}}
> Error in fbad_request(fbacc, path = file.path(id, endpoint), params = params,  : 
>   Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

I'm thinking this is likely to do factors on my end such as being in developer mode for my FB app and accessing from a local machine? Not sure, but thought I'd double check here. Thanks!

**Comment by daroczig** [comment]
Can you try the same query without the `fbRads::` part?

https://github.com/cardcorp/fbRads/blob/master/R/fb_ad.R#L169 looks for the function name -- and misses `fbRads::fbad_list_ad` as expects `fbad_list_ad`. It's easy to fix and add support for this, but 
- First, I'd like to make sure that it indeed resolves your problem.
- And may I ask why you want to reference the function name in such way?

**Comment by scottyha** [comment]
Thanks for responding!

Yup. That did it. Rookie mistake! Thank you :)

**Comment by daroczig** [comment]
Thanks for reporting back so quickly.
Based on the above commits, now you should be able to call the function with the colons as well, although I do not suggest that :) Please reopen if the above fixed does not seem to work (note: the fixes are in the `v2.5` branch).
