### ISSUE TITLE
This is a temporary FB Error

### ISSUE THREAD

**Issue by lucasdedavid** [daroczig/fbRads#110]
Is anyone else having this issue?

```
ERROR [2018-10-15 18:21:37] This is a temporary "" FB error.
INFO [2018-10-15 18:21:39] Retrying query for the 1  st/nd/rd time
ERROR [2018-10-15 18:22:09] This is a temporary "" FB error.
INFO [2018-10-15 18:22:11] Retrying query for the 2  st/nd/rd time
ERROR [2018-10-15 18:22:42] This is a temporary "" FB error.
INFO [2018-10-15 18:22:44] Retrying query for the 3  st/nd/rd time
ERROR [2018-10-15 18:23:14] This is a temporary "" FB error.
```

I can't get any more data.

**Comment by daroczig** [comment]
It happens when FB returns a "API Unknown" (1) or "API Service" (2) error as `error$code`. Try reproducing the in the Graph API Explorer at https://developers.facebook.com/tools/explorer and open a ticket at FB. please reopen if it turns out to be an `fbRads` issue, but I don't think so.
