### ISSUE TITLE
Cannot connect to the Marketing API through R

### ISSUE THREAD

**Issue by ArbenKqiku** [daroczig/fbRads#115]
Hi, 

I cannot connect to the Marketing API aspp as in order to manage ads from a Marketing API app it is necessary to add a platform. The platforms available are: facebook games, website, android, iOS, windows apps, pages, xbox or playstation. None of these platforms is necessary for me, I only want to manage my ads from R.

I would really really really appreciate if you could help me :)

Thank you very much.

**Comment by daroczig** [comment]
I've just updated a step at https://github.com/daroczig/fbRads#creating-a-facebook-app--connect-with-oauth-token -- please review and confirm you have followed those steps. I've just tried this and seems to work.

**Comment by ArbenKqiku** [comment]
Hey man,

I was finally able to connect to the Marketing API :) thank you very much for your help.

I recommend to change the version in the code, from 3.1 to 3.2 (the current version of Facebook.

Just for information, how often do you update the package?

Keep up the good work!
