### ISSUE TITLE
Service temporarily unavailable error when using fbad_init()

### ISSUE THREAD

**Issue by jmdiaz77** [daroczig/fbRads#116]
Hi, 

I'm having trouble connecting to my desired page. I retrived the token correclty following the steps mentioned in the master page, but when calling fb_init() I get an message error saying " Service temprarily unavailable"

The error message I get when calling fbad_init('XXXXXXXXXXXX', tkn,version = '3.1') is:

TRACE [2019-02-11 13:04:02] Initializing connection to account XXXXXXXXXXXX via API v3.2
ERROR [2019-02-11 13:04:02] URL:  https://graph.facebook.com/v3.2/act_XXXXXXXXXXXX/
ERROR [2019-02-11 13:04:02] Method:  GET
ERROR [2019-02-11 13:04:02] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2019-02-11 13:04:02] Header: {"x-ad-account-usage":["{\"acc_id_util_pct\":1.67}"],"x-app-usage":["{\"call_count\":3,\"total_cputime\":0,\"total_time\":0}"],"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"(#2) Service temporarily unavailable\""],"Content-Type":["application/json; charset=UTF-8"],"facebook-api-version":["v3.2"],"Strict-Transport-Security":["max-age=15552000; preload"],"Pragma":["no-cache"],"x-fb-rev":["4753726"],"Access-Control-Allow-Origin":["*"],"Cache-Control":["no-store"],"x-fb-trace-id":["Ct3QGBU6RIs"],"x-fb-request-id":["AqnJFhtiS2thl3djFoypSJt"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"X-FB-Debug":["ql/+MxkRZyKmr91ujbpCNoqQBRH9vFZ39kXEJ6nSNKWzKsFg/2XWN6ucccheMg+ogmUSSikTz6pgJpvZUHVevA=="],"Date":["Mon, 11 Feb 2019 19:03:59 GMT"],"Connection":["keep-alive"],"Content-Length":["140"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2019-02-11 13:04:02] Body: {"error":{"message":"(#2) Service temporarily unavailable","type":"OAuthException","is_transient":true,"code":2,"fbtrace_id":"Ct3QGBU6RIs"}}
ERROR [2019-02-11 13:04:02] This is a temporary "OAuthException" FB error: (#2) Service temporarily unavailable
INFO [2019-02-11 13:04:04] Retrying query for the 1  st/nd/rd time
ERROR [2019-02-11 13:04:04] URL:  https://graph.facebook.com/v3.2/act_XXXXXXXXXXXX/
ERROR [2019-02-11 13:04:04] Method:  GET
ERROR [2019-02-11 13:04:04] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2019-02-11 13:04:04] Header: {"x-ad-account-usage":["{\"acc_id_util_pct\":2.67}"],"x-app-usage":["{\"call_count\":3,\"total_cputime\":0,\"total_time\":0}"],"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"(#2) Service temporarily unavailable\""],"Content-Type":["application/json; charset=UTF-8"],"facebook-api-version":["v3.2"],"Strict-Transport-Security":["max-age=15552000; preload"],"Pragma":["no-cache"],"x-fb-rev":["4753978"],"Access-Control-Allow-Origin":["*"],"Cache-Control":["no-store"],"x-fb-trace-id":["DX9nMjP+KR8"],"x-fb-request-id":["AMag9NYW0E3j9ROvu_8kNoM"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"X-FB-Debug":["G13bOxV8/UdvxhytTdQKwgA9H9kZRlPCro6bsQVL7TCtQ3R1yXYOQGrFP/5uwgpKZqBaDFEKIhfFyhOA45LVMw=="],"Date":["Mon, 11 Feb 2019 19:04:01 GMT"],"Connection":["keep-alive"],"Content-Length":["140"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2019-02-11 13:04:04] Body: {"error":{"message":"(#2) Service temporarily unavailable","type":"OAuthException","is_transient":true,"code":2,"fbtrace_id":"DX9nMjP+KR8"}}
ERROR [2019-02-11 13:04:04] This is a temporary "OAuthException" FB error: (#2) Service temporarily unavailable
INFO [2019-02-11 13:04:06] Retrying query for the 2  st/nd/rd time
ERROR [2019-02-11 13:04:07] URL:  https://graph.facebook.com/v3.2/act_XXXXXXXXXXXX/
ERROR [2019-02-11 13:04:07] Method:  GET
ERROR [2019-02-11 13:04:07] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2019-02-11 13:04:07] Header: {"x-ad-account-usage":["{\"acc_id_util_pct\":3.33}"],"x-app-usage":["{\"call_count\":3,\"total_cputime\":0,\"total_time\":0}"],"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"(#2) Service temporarily unavailable\""],"Content-Type":["application/json; charset=UTF-8"],"facebook-api-version":["v3.2"],"Strict-Transport-Security":["max-age=15552000; preload"],"Pragma":["no-cache"],"x-fb-rev":["4753726"],"Access-Control-Allow-Origin":["*"],"Cache-Control":["no-store"],"x-fb-trace-id":["F0ZN3bz9plW"],"x-fb-request-id":["AtzxaIiU_lTlZlnE1xGp0bO"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"X-FB-Debug":["N4tRt9t0KNJX2al/mRJK1zzKsL5j92cvShlucgrjMiDoy8hAXSLjIRELFJy1q2r755Uk7Xt+kYn/M3leAyG+Yg=="],"Date":["Mon, 11 Feb 2019 19:04:04 GMT"],"Connection":["keep-alive"],"Content-Length":["140"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2019-02-11 13:04:07] Body: {"error":{"message":"(#2) Service temporarily unavailable","type":"OAuthException","is_transient":true,"code":2,"fbtrace_id":"F0ZN3bz9plW"}}
ERROR [2019-02-11 13:04:07] This is a temporary "OAuthException" FB error: (#2) Service temporarily unavailable
INFO [2019-02-11 13:04:09] Retrying query for the 3  st/nd/rd time
ERROR [2019-02-11 13:04:09] URL:  https://graph.facebook.com/v3.2/act_209531642397450/
ERROR [2019-02-11 13:04:09] Method:  GET
ERROR [2019-02-11 13:04:09] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2019-02-11 13:04:09] Header: {"x-ad-account-usage":["{\"acc_id_util_pct\":4.33}"],"x-app-usage":["{\"call_count\":3,\"total_cputime\":0,\"total_time\":0}"],"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"(#2) Service temporarily unavailable\""],"Content-Type":["application/json; charset=UTF-8"],"facebook-api-version":["v3.2"],"Strict-Transport-Security":["max-age=15552000; preload"],"Pragma":["no-cache"],"x-fb-rev":["4753726"],"Access-Control-Allow-Origin":["*"],"Cache-Control":["no-store"],"x-fb-trace-id":["HAxUzdW/S9J"],"x-fb-request-id":["AN3v2SONSkFQh_6J6UND_Md"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"X-FB-Debug":["VZnHAf414IQWHZ5oYJA3PD4/mlIBZAHVHVzOZDplBpSSAwuLxRdFJlkuW+XfhP0N6dNE56xKlAmcER+FWBsajg=="],"Date":["Mon, 11 Feb 2019 19:04:06 GMT"],"Connection":["keep-alive"],"Content-Length":["141"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2019-02-11 13:04:09] Body: {"error":{"message":"(#2) Service temporarily unavailable","type":"OAuthException","is_transient":true,"code":2,"fbtrace_id":"HAxUzdW\/S9J"}}
ERROR [2019-02-11 13:04:09] This is a temporary "OAuthException" FB error: (#2) Service temporarily unavailable
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  (#2) Service temporarily unavailable

**Comment by daroczig** [comment]
This is an FB API error that I cannot resolve -- please open a support ticket at Facebook or wait until the issue is resolved on their end :/
