### ISSUE TITLE
Is there a way to get a preview image as seen on FB (not thumbnail) of a video?

### ISSUE THREAD

**Issue by laresbernardo** [daroczig/fbRads#117]
Hello! Is there a way to get a preview image url of a post/ad no matter if it's a video or an image? Hope you can help me, thanks! 👍

**Comment by daroczig** [comment]
Sure: https://developers.facebook.com/docs/marketing-api/generatepreview/v3.3

There's also a `fbad_preview_ad` helper to hit that, but honestly I have not used for years by now, so no recent hands-on experience. Please open a new ticket if you run into any issues.
