### ISSUE TITLE
Question: Targeting

### ISSUE THREAD

**Issue by scottyha** [daroczig/fbRads#12]
Hi there,

I'm still loving this package. I'm new to R, and your package is the first one I'm using and it's definitely getting me much more involved.

I'm stumped and can't figure out targeting for new ad sets.

I've viewed your presentation, and it deals with custom audiences. How does one set other targeting though?

for example:

``` r
countries = AU
age_min = 28
age_max = 50
```

How do I correctly put this in R so that FB API picks it up? Nothing I'm doing seems to work.

```
 $ name             : chr "Test"
 $ optimization_goal: chr "LINK_CLICKS"
 $ billing_event    : chr "LINK_CLICKS"
 $ bid_amount       : num 100
 $ campaign_id      : chr "6041163821559"
 $ configured_status: chr "ACTIVE"
 $ daily_budget     : num 1000
 $ targeting        :Class 'json'  chr "[[\"countries\",\"AU\"]]"
ERROR [2016-03-13 20:27:34] Header: {"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"(#100) Your audience targeting is incomplete. Select at least one location,\\n        or choose a Custom Audience.\""],"Access-Control-Allow-Origin":["*"],"Content-Type":["application/json; charset=UTF-8"],"X-FB-Trace-ID":["E1j8+00q6cu"],"X-FB-Rev":["2227162"],"Pragma":["no-cache"],"Cache-Control":["no-store"],"Facebook-API-Version":["v2.5"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"Vary":["Accept-Encoding"],"X-FB-Debug":["zc2f3XyTCtgUNINPNAobwh13Sll8bwdjgJK32io4WOfas/NkWzej/IX6oC1EAMvv/Ddli/YXkDeLd4CP9eawew=="],"Date":["Sun, 13 Mar 2016 09:27:34 GMT"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2016-03-13 20:27:34] Body: {"error":{"message":"(#100) Your audience targeting is incomplete. Select at least one location,\n        or choose a Custom Audience.","type":"OAuthException","code":100,"fbtrace_id":"E1j8+00q6cu"}}
Error in fbad_request(fbacc, path = paste0("act_", fbacc$account_id, ifelse(fb_api_version() <  : 
  (#100) Your audience targeting is incomplete. Select at least one location,
        or choose a Custom Audience.
```

Thanks for the help!

**Comment by daroczig** [comment]
Can you please share how you defined the target? That JSON seems to be malformed (array instead of list) and missing the `geo_locations` parent. For details on all the available options for targeting, see the FB docs at https://developers.facebook.com/docs/marketing-api/targeting-specs/v2.5

But to answer your original question, please see the last slides of the presentation after the "success kid" slide (not shown at the webinar) at http://bit.ly/domino-webinar-fbRads -- there you can see some targeting examples. In short, the country should be defined something like:

``` r
target <- list(geo_locations = list(countries = 'AU'))
```

I hope this helps, so closing the ticket -- but please feel free to reopen if you'd need further help with this.

**Comment by scottyha** [comment]
Thanks for helping again, I appreciate it!

There's a slight adjustment to the code you provided, but here's how I got it to work:

newAdset <- fbad_create_adset(
  fbacc,
  name = "Test",
  bid_type = "CPC",
  campaign_status = "PAUSED",
  bid_amount = 100,
  daily_budget = 1000,
  campaign_id = newCampaign,
  optimization_goal = "LINK_CLICKS",
  billing_event = "LINK_CLICKS",
  targeting = list(geo_locations = list(countries = list('AU')))
)

**Comment by daroczig** [comment]
Cool :) I'm glad you got it working.
