### ISSUE TITLE
Request - Ad Rules Management

### ISSUE THREAD

**Issue by debsbalme** [daroczig/fbRads#136]
Hi, 
Been using the package for insights and ad management, and can't see anywhere the ability to manage the Ad Rules as part of the Ad Rules Engine?  is that something that can be added? or is there a solution currently?

Thanks

**Comment by daroczig** [comment]
Sorry, I don't have experience with FB's Ad Rules Engine, but if there's a related API endpoint, it should be definitely doable. Look at `fbRads:::fbad_request` for passing arbitrary calls to the Marketing API -- happy to review a PR if you come up with some wrapper functions, but I'm not likely to be able to get time to work on this actively in the near future.

**Comment by debsbalme** [comment]
Ok great thanks will take a look


Sent from my iPhone

On Feb 19, 2021, at 17:05, Gergely Daróczi <notifications@github.com> wrote:

﻿
Sorry, I don't have experience with FB's Ad Rules Engine, but if there's a related API endpoint, it should be definitely doable. Look at fbRads:::fbad_request for passing arbitrary calls to the Marketing API -- happy to review a PR if you come up with some wrapper functions, but I'm not likely to be able to get time to work on this actively in the near future.

**Comment by debsbalme** [comment]
fbRads:::fbad_request  is working with the endpoint as you suggested! thanks
