### ISSUE TITLE
Error in fbad_update_ad

### ISSUE THREAD

**Issue by SSJchen** [daroczig/fbRads#14]
Hi,

When I use `fbad_update_ad(fbacc, id,list("name"="Jeff"))` to change my ad's name, it will occur error:

>  Error in fbad_request(fbacc, path = id, params = list(...), method = "POST") : 
>   This is a bug in the fbRads package. Please report on GitHub with a detailed output: STRING_ELT() can only be applied to a 'character vector', not a 'list"

How could I fix it?

**Comment by scottyha** [comment]
Hey there. I might be able to help:

Try this instead:

`fbad_update_ad(fbacc, id, name = "NEW NAME")``

An example of this in practice:

```
x <- fbad_list_ad(fbacc, fields = 'name')

y <- as.character(x$id[1])

fbad_update_ad(fbacc, y, name = "MY NEW NAME")

fbad_read_ad(fbacc, y, fields = "name")`

```

```
      name            id
1 MY NEW NAME 6041*****9
```

Hope this helps!

**Comment by daroczig** [comment]
That's right, thanks @scottyha for the pointer!
The `fbad_update_ad` function takes the FB parameters as `...`, so no need to wrap those in a `list`.

Please let me know how it works.

**Comment by SSJchen** [comment]
Thank you all, it helps me a lot!
