### ISSUE TITLE
Not able to get insight data for more than 7 days

### ISSUE THREAD

**Issue by vivek1219** [daroczig/fbRads#15]
I am using fb_insight() to get data at campaign level for last 30 days/lifetime, but its giving me below error. 

**ERROR [2016-05-23 17:10:25] This is a temporary "" FB error.
INFO [2016-05-23 17:10:28] Retrying query for the 1  st/nd/rd time**

But when i run for last 7 days, it doesnt show any error and fetch data easily. 
Below is my query - 
fb_insights(fbacc, time_increment = 1 ,date_preset = 'last_7_days', level = 'campaign')

Can somebody tell even if it is possible with fbRads to get data for more number of days or not? If yes, help me understand if i am doing something wrong here.

Another issue i am facing is with the use of time_range function in fb_insight(). I know, it needs a different thread as this is different question but i am not able to set 'since' and 'until' values in time_range/time_ranges.

**Comment by daroczig** [comment]
It is absolutely possible to get data for the past 7 days and your related R command seems to be OK -- but unfortunately, Facebook is currently having issues with responding to these queries, see eg
- https://developers.facebook.com/bugs/1512774485695883/
- https://developers.facebook.com/bugs/216081378782081/

Which bug is causing production issues on my end as well. Unfortunately, there's not much to do as this is a problem in FB's platform, so please report at the related threads that you also have this issue.

About `time_range`: that's doable as well, eg for the past 2 weeks:

``` r
toJSON(data.frame(
            since = as.character(Sys.Date() - 14),
            until = as.character(Sys.Date())), auto_unbox = TRUE)
```

I'm closing this ticket, but please reopen / create a new one if you have any questions.
