### ISSUE TITLE
fbRads Facebook API 2.6

### ISSUE THREAD

**Issue by Janvh** [daroczig/fbRads#19]
Hi,

I'v loaded fbRads_0.2. I get the following error:

`Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.6.`

Is there a new version I can use with API v2.6? Or how can I select to use API v2.5?

Thanks

**Comment by daroczig** [comment]
Sorry for the long delay with this, but `fbRads` now defaults to v2.6 since d7f0acc461524a6c00d6eb02b9914616d27b69c1
