### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by igbuch** [daroczig/fbRads#2]
Hi,

Trying to run `fbad_init()` for the first time and I get the following error message that I'm trying to understand.

```
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  :  This is a bug in the fbRads package. 
Please report on GitHub: SSL certificate problem: unable to get local issuer certificate
```

Steps I followed:
- Created the Facebook App
- Added the Ads account ID to the list of Authorized Ad Account IDs of the app
- Authenticated via R and got an access token -- requested access scope `ads_read`

I noticed the version of the API the package attempts to hit is 2.3 (current is v2.4). This is hard-coded in `fb_init.R`. However, if I hit v2.3 of the API via url it says it's deprecated.

```
https://graph.facebook.com/v2.3/act_{my_id}/insights?level=account&access_token={my_token}

{
   "error": {
      "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version.",
      "type": "OAuthException",
      "code": 2635
   }
}
```

But if I hit v2.4 I get a response with results. Same `act_id`, same `access_token`.

Could my original error be just a versioning issue?

Thanks!
## 

```
> version

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          1.2                         
year           2014                        
month          10                          
day            31                          
svn rev        66913                       
language       R                           
version.string R version 3.1.2 (2014-10-31)
nickname       Pumpkin Helmet 
```

**Comment by daroczig** [comment]
Thanks for this report, I will have a look on the problem on Windows in the near future -- I suspect an RCurl cert issue specific to Win, as v2.3 should be fine until October.

**Comment by daroczig** [comment]
Can you please reinstall the most recent dev version of the package and verify if this small modification resolved this issue? Thanks, Gergely
