### ISSUE TITLE
Problem with Access Tokens

### ISSUE THREAD

**Issue by 13bzhang** [daroczig/fbRads#20]
I followed your directions on the GitHub main page but I am still having issues with getting access tokens. I'm using v2.6 of the Facebook API. See below for my code and error messages. Do you think it's a problem with the new FB API version?

``` r
> app <- oauth_app('facebook', a, b)
> Sys.setenv('HTTR_SERVER_PORT' = '1410/')
> tkn <- oauth2.0_token(
+   oauth_endpoints('facebook'), app, scope = 'ads_management',
+   type  = 'application/x-www-form-urlencoded', cache = FALSE)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Bad Request (HTTP 400). Failed to get an access token.
> tkn <- tkn$credentials$access_token
Error: object 'tkn' not found
```

**Comment by 13bzhang** [comment]
I was able to get the Access Token to work with my other app account that had a real web page. I am still confused to what is the problem.

**Comment by Janvh** [comment]
Hi,

What do you mean by the " other app account that had a real web page"? 

Thanks

**Comment by CaptainStoz** [comment]
I too had the same issue, I think it has to do with the latest version of httr and the port not needing to be defined for local host.  If you just leave off the line 
Sys.setenv('HTTR_SERVER_PORT' = "1410/")
it should work just great.

**Comment by daroczig** [comment]
Thanks for this report. It seems that there were some UI changes at FB, so pushed some updates regarding this at 87ad33f
