### ISSUE TITLE
Deprecated User Instructions

### ISSUE THREAD

**Issue by 13bzhang** [daroczig/fbRads#21]
The instructions on the main page says:

> In the "Settings/Advanced" tab, add http://localhost:1410/ as the "Valid OAuth redirect URIs". Click "Save Changes".

But the Facebook app interface seems to have changed. Now you need to get Facebook Log under Products and set it up that way. 

<img width="1122" alt="screen shot 2016-06-17 at 12 00 05 pm" src="https://cloud.githubusercontent.com/assets/6131842/16156627/1f75072e-3483-11e6-8bcf-900cebc3485f.png">

**Comment by daroczig** [comment]
Thanks a lot, updated docs at 87ad33f
