### ISSUE TITLE
Identify all accounts for business manager

### ISSUE THREAD

**Issue by danwwilson** [daroczig/fbRads#26]
For people who manage multiple accounts, is there a way to identify all the account IDs based on a business manager ID?

I've changed the scope of access to align with version 2.7 scopes for `business_management` as identified [here](https://developers.facebook.com/docs/marketing-api/businessmanager/v2.7)

``` r
tkn <- oauth2.0_token(
  oauth_endpoints('facebook'), app, scope = 'business_management',
  type  = 'application/x-www-form-urlencoded', cache = FALSE)
```

There is more documentation on how to GET all the accounts that the business manager owns on [this](https://developers.facebook.com/docs/marketing-api/businessmanager/assets/v2.7) page at the heading  _Viewing business manager owned ad accounts_

Maybe this could be an enhancement. I'm not too sure how to go about creating this as a function

**Comment by daroczig** [comment]
This is also doable with the currently supported v2.6: https://developers.facebook.com/docs/marketing-api/businessmanager/assets/v2.6#adaccounts-view

Thanks for this feature request, this seems to be easily doable, please expect a new function to be pushed to th package in the next few days.

**Comment by danwwilson** [comment]
Super! Looking forward to give it a test.

**Comment by daroczig** [comment]
Sorry for the long delay with this. It seems that this feature is pretty easily accessible already:

``` r
fromJSON(fbRads:::fbad_request(path = file.path(business_id, 'adaccounts')))
```

But coming up with a good name for the function is much more difficult :) So I'm closing this for now as I don't have any good suggestion on how to name this + related API wrappers, but open to ideas and happy to add to the package if someone is willing to help with it.
