### ISSUE TITLE
Time Ranges with fb_insights

### ISSUE THREAD

**Issue by danwwilson** [daroczig/fbRads#27]
Sorry if this is just me being daft, however I am having trouble with the `time_range` variable for the insights method.

``` r
fb_insights(time_range = "{'since'=>'2016-05-30','until'=>'2016-07-31'}", level = 'ad', fields = "['date_start','date_stop','account_name','campaign_name','ad_name','impressions','spend','clicks','ctr','reach','frequency','cost_per_unique_click','objective','ad_id','account_id']")
```

I can get it to work with the  `date_preset`, however I get an error message with the `time_range`

Error in fb_insights(time_range = "{'since'=>'2016-05-30','until'=>'2016-07-31'}",  : 
  (#100) param time_range must be non-empty.

Any help on how to structure the time_range would be super.

**Comment by daroczig** [comment]
See eg the below JSON generated by the `jsonlite` package:

``` r
> library(jsonlite)
> toJSON(data.frame(
+             since = as.character(Sys.Date() - 14),
+             until = as.character(Sys.Date())), auto_unbox = TRUE)
[{"since":"2016-07-19","until":"2016-08-02"}] 
```

**Comment by danwwilson** [comment]
Thanks for that.

For anyone else who is looking for how to use the time ranges the below code works.

``` r
fb_insights(time_range = "{'since'=>'2016-05-30','until'=>'2016-07-31'}", level = 'ad', fields = "['date_start','date_stop','account_name','campaign_name','ad_name','impressions','spend','clicks','ctr','reach','frequency','cost_per_unique_click','objective','ad_id','account_id']")
```

**Comment by SSJchen** [comment]
I use this code:

`fb_insights(time_range = "{'since'=>'2016-05-30','until'=>'2016-07-31'}", level = 'ad', fields = "['date_start','date_stop','account_name','campaign_name','ad_name','impressions','spend','clicks','ctr','reach','frequency','cost_per_unique_click','objective','ad_id','account_id']"`

but occur an error like:
**(#100) param time_range must be non-empty.**

Could I fix it?

**Comment by daroczig** [comment]
Ah, sorry, I've just realized both of you are trying to use the `time_range` argument, while I'm always using `time_ranges` -- which takes an array instead of a single time window. Please find below a reproducible working example using the latter argument with only one time period:

``` r
library(jsonlite)
fb_insights(time_ranges = toJSON(data.frame(
                since = as.character(Sys.Date() - 14),
                until = as.character(Sys.Date())), auto_unbox = TRUE),
            level = 'ad',
            fields = toJSON(c('date_start', 'date_stop', 'account_name',
                              'campaign_name', 'ad_name', 'impressions',
                              'spend', 'clicks', 'ctr', 'reach', 'frequency',
                              'cost_per_unique_click', 'objective', 'ad_id',
                              'account_id')))
```

**Comment by SSJchen** [comment]
Thanks for your help.
It works using`time_ranges,` but it will ignore `time_increment`.
Hence, I couldn't get a daily date within some time range.

**Comment by daroczig** [comment]
Ah, OK, then simply modify the `data.frame` part to `list`:

``` r
fb_insights(time_range = toJSON(list(
                since = as.character(Sys.Date() - 14),
                until = as.character(Sys.Date())), auto_unbox = TRUE),
            level = 'ad',
            fields = toJSON(c('date_start', 'date_stop', 'account_name',
                              'campaign_name', 'ad_name', 'impressions',
                              'spend', 'clicks', 'ctr', 'reach', 'frequency',
                              'cost_per_unique_click', 'objective', 'ad_id',
                              'account_id')))
```

**Comment by danwwilson** [comment]
my bad. I pasted the wrong code in my reply. If you don't want to use the `toJSON` code, this is what I did actually get working.

``` r
startdate <- "2016-01-01"
fb_insights(time_range = paste0("{'since':'",startdate,"','until':'",Sys.Date(),"'}"),
                        time_increment = 1, level = 'ad', fields = "['date_start',
                        'date_stop','account_name','campaign_name','ad_name',
                        'impressions','spend','clicks','ctr','reach','frequency',
                        'cost_per_unique_click','objective','ad_id','campaign_id',
                        'account_id']")
```

**Comment by SSJchen** [comment]
Thx, it works!
