### ISSUE TITLE
You are calling a deprecated version of the Ads API. Please update to the latest version.

### ISSUE THREAD

**Issue by igbuch** [daroczig/fbRads#3]
Thanks for addressing #2.

But I'm now getting the "calling a deprecated version of the Ads API" error I had mentioned.

![image](https://cloud.githubusercontent.com/assets/9340069/8699316/b2fcd4c4-2ad2-11e5-886b-e90bd97131a4.png)

Thanks!

**Comment by daroczig** [comment]
Ah, right, now I understand what's the problem: if you create a new FB application, it will require to be used with the most recent stable version of the API. So if you created the FB application before the 8th of July, it works fine with v2.3 until October, but any newer app already requires v2.4

Anyway, all features of the packages (except for reportstats) should work fine with updating the hard-coded version number at https://github.com/cardcorp/fbRads/blob/master/R/fb_init.R#L3

If you need this urgently, I suggest forking the repo and updating that only one character -- I will be able to come up with a more elegant solution early next week (as the `adreportstats` endpoint is deprecated with the new API -- although I think the Insights endpoint is not yet perfect for production).

**Comment by igbuch** [comment]
Oh I see.

I just forked it and updated the hard-coded version number.

Also had to remove field daily_speed_limit as it was trowing a deprecated
error... Might be able to use it for now, thanks.

Looking forward to the updated version though.

**Comment by daroczig** [comment]
Thanks, the `daily_spent_limit` was indeed removed from the ad level. Full list of changes: https://developers.facebook.com/docs/marketing-api/changelog#v2_4

Support for this new version is coming soon. The only limitation now is the deprecation of the old statistics/reports API endpoints -- for which first I have to remove the dependency on always providing the `fbacc` object, then update the general FB query function to use the API version from the internally stored `fbacc` object and do some checks on the actual FB API version number.

**Comment by daroczig** [comment]
This update turned out to be a lot more complex then initially planned, but now you can use either v2.3 or v2.4 -- please let me know how it works for you and if you see any strange behavior after this update: https://github.com/cardcorp/fbRads/compare/ede3af4f03926d1489b8304bcfcdb41f242365c6...d57e773cd9983975693e8f0bf8d4cee917159dbd
