### ISSUE TITLE
Issues with fbad_create_creative

### ISSUE THREAD

**Issue by meh256** [daroczig/fbRads#31]
HI,
I just started using this package I and I really like it. I am having some issue with trying to associate page id with ad creative. The follow command does not work when I include object_id 

creative <- fbad_create_creative(
  name = "Career Networking. Solved.",
  body = paste0('Professional networking made easy. User Xpertly to get inros to peeps you in your field'),
  title = 'Career networking. Solved',
  object_url = url,
  image_hash = img,
  object_id = list(1595692097387723)
)

Tried it as character and interger but did not work. 

Error Thrown: 
Error in fbad_request(fbacc, path = paste0("act_", fbacc$account_id, "/adcreatives"),  : 
  This is a bug in the fbRads package. Please report on GitHub with a detailed output: STRING_ELT() can only be applied to a 'character vector', not a 'list'

**Comment by daroczig** [comment]
Thanks for reporting this confusing part of the docs -- the list of default fields returned by FB was pretty outdated. I hope the updated examples make more sense.

**Comment by daroczig** [comment]
The object_id should be numeric. For such large integers, it's better to load the `bit64` package. What error message did FB returned? I suspect something like `The object you are trying to promote is ambiguous. You must specify only one promoted object. You specified the following: object_id, object_url.`. Did you try either with `object_url` or `object_id`?

**Comment by meh256** [comment]
Thanks for the tip. Loaded the bit64 package but that didn't work either. I get an "invalid parameter" error when I try to use object_id = 1595692097387723 

Specifically this error: 

Error in fbad_request(fbacc, path = paste0("act_", fbacc$account_id, "/adcreatives"),  : 
  Invalid parameter

**Comment by daroczig** [comment]
Did you try the query without setting the `object_url`? So having the `object_id` but not having the `object_url`?

**Comment by meh256** [comment]
fml! That worked. Thank you for your help. By the way, are you the one who presented this at the LA R UseRs group meetup? This is a badass package.

**Comment by daroczig** [comment]
Cool, I'm glad it worked after all.

And yeah, @ajzz and I presented the package briefly last year at the LA RUG -- thanks for your kind words :)
