### ISSUE TITLE
invalid character inside string 

### ISSUE THREAD

**Issue by simran-k** [daroczig/fbRads#32]
`> #l <- fbad_list_ad(fields = c('id','ad_review_feedback','adlabels', 'adset','adset_id','campaign', 'campaign_id', 'configured_status', 'conversion_s .... [TRUNCATED]`

I get an error; 

```
Error: lexical error: invalid character inside string.
           \"We <3 Choker-necks! Do you? Shop the hottest...\"","updat
                     (right here) ------^
```

I am trying to import my list of campaigns and above string is a campaign name. 

Why do I get this error? Which character is the problem here?
The entire string is like this:

`Ad Set: Post: "We <3 Choker-necks! Do you? Shop the hottest..."`

**Comment by daroczig** [comment]
It seems to me that FB returns an invalid JSON just like in #23
Can you run the function (or maybe `fbRads::fbad_request`) with `debugonce`  to see the actual FB response?

**Comment by simran-k** [comment]
@daroczig : What would be the path here?

**Comment by simran-k** [comment]
@daroczig : Is there a solution/workaround for this yet?
