### ISSUE TITLE
how to use breakdowns while querying data from facebook

### ISSUE THREAD

**Issue by simran-k** [daroczig/fbRads#33]
Facebook gives a breakdown feature in its insights API. 

[https://developers.facebook.com/docs/marketing-api/insights/breakdowns/v2.7
](fbInsights-breakdowns)
How to use this in fbRads?

**Comment by daroczig** [comment]
`fb_insights` passes all args to the FB API, so simply specify the `breakdowns` parameter, eg

``` r
fb_insights(date_preset = 'today', level = 'ad', breakdowns = 'age', job_type = 'async')
```

**Comment by simran-k** [comment]
@daroczig Hey, Thanks. Should there be any problem with this:     
`    FBInsightsBreakdownByPlatformAndDevice <<- fb_insights(level = 'ad', time_range=sprintf("{'since':%s,'until':%s}", paste('"', maxDate, '"', sep=''), paste('"', yesterdayDate, '"', sep='')), time_increment= 1, breakdowns = 'device_platform');
`
?

I don't get data for this. Did I add anything wrong here?
