### ISSUE TITLE
Bad Request (HTTP 400). Failed to get an access token. Still.

### ISSUE THREAD

**Issue by a0903624** [daroczig/fbRads#39]
Hi all,

I am still having a problem with access to my token! I already tried to fix this issue as you suggest in #28 and #77 but it still does not work for me. I used this code:
 library(httr)
     app <- oauth_app('facebook', 'your app id', 'your app secret')
     Sys.setenv('HTTR_SERVER_PORT' = '1410/')
     tkn <- oauth2.0_token(
         oauth_endpoints('facebook'), app, scope = 'ads_management',
         type  = 'application/x-www-form-urlencoded', cache = FALSE)
     tkn <- tkn$credentials$access_token

I've also tried to leave off the line Sys.setenv('HTTR_SERVER_PORT' = '1410/').
I also checked my OAuth Redirect URIs.
Is there any other possible solution?

Here my sessioninfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rfacebook_0.6.11 httpuv_1.3.3     rjson_0.2.15     httr_1.2.1.9000  devtools_1.12.0  RMySQL_0.10.9   
[7] DBI_0.5-1       

loaded via a namespace (and not attached):
[1] R6_2.2.0      tools_3.3.1   withr_1.0.2   curl_2.3      Rcpp_0.12.6   memoise_1.0.0 git2r_0.15.0 
[8] digest_0.6.10

Many thanks!

**Comment by daroczig** [comment]
Are you sure this in an issue with the `fbRads` package? It seems you want to use `Rfacebook` from the session info. Although I suppose both packages use the same mechanism to get an access token, but I'm not sure how can I help you here without knowing what is the exact error message. Based on these, I'm closing this ticket -- but please feel free to reopen with some more details.

**Comment by a0903624** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Oh I am sorry it seems I adress my question to the wrong person. I try to use Rfacebook and I get an error 
Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Bad Request (HTTP 400). Failed to get an access token.
I try to adress this question here:
https://github.com/pablobarbera/Rfacebook/issues/77
 
Many thanks
Best Iwona
 
 

Are you sure this in an issue with the fbRads package? It seems you want to use Rfacebook from the session info. Although I suppose both packages use the same mechanism to get an access token, but I'm not sure how can I help you here without knowing what is the exact error message. Based on these, I'm closing this ticket -- but please feel free to reopen with some more details.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cardcorp/fbRads","title":"cardcorp/fbRads","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/cardcorp/fbRads"}},"updates":{"snippets":[{"icon":"PERSON","message":"@daroczig in #39: Are you sure this in an issue with the `fbRads` package? It seems you want to use `Rfacebook` from the session info. Although I suppose both packages use the same mechanism to get an access token, but I'm not sure how can I help you here without knowing what is the exact error message. Based on these, I'm closing this ticket -- but please feel free to reopen with some more 
details."}],"action":{"name":"View Issue","url":"https://github.com/cardcorp/fbRads/issues/39#issuecomment-272153042"}}}
// ]]>

**Comment by alexgithub56** [comment]
install.packages("Rfacebook")
install.packages("RCurl")
install.packages("devtools")
library(Rfacebook)
library(RCurl)
library(devtools)
library(tidyverse)
token <- 'xxxxxx'
me <- getUsers("me", token, private_info = TRUE)
var1 <- getPage(page = "webpage", token, since = "2018/01/01", until = "2018/03/10", n = 20000)

it's work.
