### ISSUE TITLE
fbad_init: cannot coerce type 'environment' to vector of type 'character'

### ISSUE THREAD

**Issue by lordyo** [daroczig/fbRads#4]
Went through the examples in the useR! slides, and got stuck when trying to initialize the Marketing API:

note: fid is specified and removed from the error message

```
fbacc <- fbad_init(fid, tkn)
ERROR [2015-12-23 11:56:17] URL:  https://graph.facebook.com/v2.4/act_XXXXXXXX/
  ERROR [2015-12-23 11:56:17] Method:  GET
ERROR [2015-12-23 11:56:17] Params:  List of 1
$ fields: chr        "name,account_id,account_status,age,amount_spent,balance,capabilities,end_advertiser,funding_source,spend_cap,timezone_id,users"
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
                        This is a bug in the fbRads package. Please report on GitHub with a detailed output:     cannot coerce type 'environment' to vector of type 'character'
```

**Comment by daroczig** [comment]
Thanks for reporting this! Please note that the useR! slides are a bit outdated, you might have better luck with the updated slides presented at EARL -- available at http://bit.ly/fbRads-at-EARL2015

Can you please double check if `fid` is a string or numeric value and if `tkn` is a string? The returned error message suggests one of those might be off.

Also, if you registered the FB app later than Oct 7 2015, v2.4 might not be available, so can you try v2.5 via:

``` r
fbad_init(fid, tkn, version = '2.5')
```

**Comment by lordyo** [comment]
Thanks for the updated slides and the tips - I'm especially happy about the new `fb_insights` function! I will need to check my business machine for the answers to your questions, but I'm pretty sure `fid` is a character string.

**Comment by lordyo** [comment]
I've checked; `fid` is a character string, `tkn` is an environment, invoked by

```
tkn <- oauth2.0_token(
  oauth_endpoints('facebook'), app, scope = 'ads_management',
  type = 'application/x-www-form-urlencoded')
```

Class() gives me:

```
> class(tkn)
[1] "Token2.0" "Token"    "R6" 
```

**Comment by daroczig** [comment]
Thank you @lordyo, this makes sense. I think you might missed one line from the EARL conf slides after getting the token with `oauth2.0_token`:

``` r
tkn <- tkn$credentials$access_token
```

So that `tkn` is the actual string and not `httr`-related environment. I think this will resolve your problem -- looking forward to your kind feedback.

**Comment by daroczig** [comment]
Closing this as the above seems to resolve the symptoms -- but please reopen if not.
