### ISSUE TITLE
bug in fbrads package

### ISSUE THREAD

**Issue by simran66** [daroczig/fbRads#44]
```
ERROR [2017-02-06 04:04:12] URL:  https://graph.facebook.com/v2.7/act_784298674999592/
ERROR [2017-02-06 04:04:12] Method:  GET
ERROR [2017-02-06 04:04:12] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,balance,capabilities,end_advertiser,funding_source,spend_cap,timezone_id,users"
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  This is a bug in the fbRads package. Please report on GitHub with a detailed output: Failed to connect to graph.facebook.com port 443: Connection timed out
Calls: tapply ... fbad_init -> fbad_get_adaccount_details -> fbad_request
```

I get this error. My requests have continuously been failing with a cron though works when executed manually. It has worked fine before for a very long time

**Comment by daroczig** [comment]
I'm pretty sure this is a temporary network error either on your or FB's end, similarly to #41 -- so closing, but please reopen if you see that for a longer period of time and can reproduce the problem.

**Comment by simran66** [comment]
I guess not. I have seen same error for like8 a week.

On 7 Feb 2017 02:10, "Gergely Daróczi" <notifications@github.com> wrote:

I'm pretty sure this is a temporary network error either on your or FB's
end, similarly to #41 <https://github.com/cardcorp/fbRads/issues/41> -- so
closing, but please reopen if you see that for a longer period of time and
can reproduce the problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cardcorp/fbRads/issues/44#issuecomment-277806436>, or mute
the thread
