### ISSUE TITLE
Using fb_insights to get Delivery 

### ISSUE THREAD

**Issue by ringator144** [daroczig/fbRads#48]
Hi there,

I am using the `fb_insights()` to get colomuns of a report, however I am not able to get the Delivery of each ad (see attached).
Since I am using a breakdown parameter, it's not accurate to use `fbad_read_ads()` or `fbad_list_ads()`. Is this possible using `fb_insights()`?

```
list <- fb_insights(date_preset ='last_7_days', time_increment='1', level = 'ad' , breakdowns ='hourly_stats_aggregated_by_advertiser_time_zone', 
                        fields = toJSON(c('date_start','date_stop', 'campaign_name', 'adset_name','ad_name','clicks','reach','spend','impressions')))
    

```
![2017-02-15 09_20- 18 adverts manager](https://cloud.githubusercontent.com/assets/25732234/22952297/86822f90-f360-11e6-8fd7-a640479b7024.jpg)

**Comment by daroczig** [comment]
Please check Facebook's related docs on the available fields in the Insights API endpoint at https://developers.facebook.com/docs/marketing-api/insights/fields
