### ISSUE TITLE
fbad_init(fid, tkn): SSL: CA certificate set, but certificate verification is disabled

### ISSUE THREAD

**Issue by albertabello** [daroczig/fbRads#5]
Hello,

I am getting this issue when running fbad_init(fid, tkn):

ERROR [2016-01-27 19:34:38] URL:  https://graph.facebook.com/v2.4/act_xxx/
ERROR [2016-01-27 19:34:38] Method:  GET
ERROR [2016-01-27 19:34:38] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,balance,capabilities,end_advertiser,funding_source,spend_cap,timezone_id,users"
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  This is a bug in the fbRads package. Please report on GitHub with a detailed output: SSL: CA certificate set, but certificate verification is disabled
Además: Warning message:
In curlSetOpt(..., .opts = .opts, curl = h, .encoding = .encoding) :
  Error setting the option for # 2 (status = 4) (enum = 10097) (value = 0x11757ae30): A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision. SSL: CA certificate set, but certificate verification is disabled

**Comment by daroczig** [comment]
Can you please share your `devtools::session_info()` so that I can try to replicate this problem on your platform etc?

**Comment by albertabello** [comment]
Here you are:

 setting  value  
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0  
 ui       RStudio (0.99.491)  
 language (EN)  
 collate  es_ES.UTF-8  
 tz       Europe/Madrid  
 date     2016-01-28                  

I am trying to do some more research about the issue from my side.

**Comment by tokumotion** [comment]
@albertabello Hey, maybe you're using the whole token, you need to get the token text this way:

token$credentials$access_token

After this, you won't get the error message.

**Comment by albertabello** [comment]
Any update? I've been trying different stuff but nothing worked so far.
Will keep trying.

**Comment by albertabello** [comment]
Fixed. There was a problem with the version of fbRads on the package repository and some outdated libraries.
Sorry i thought they all updated.

**Comment by daroczig** [comment]
Thanks for the update @albertabello

**Comment by Cpratt3000** [comment]
I have been receiving an identical error message recently.

I can reproduce this reliably by initializing and running an fbRads fb_insights() query, followed by a Google Analytics query (using RGoogleAnalytics in this case), THEN running another fbRads fb_insights query in the same session.

Terminating/restarting the R session resolves the issue. 

Anyway, here is the error and an outline of code that will reproduce this issue for me.

Nice work on the package--posting here since your error text helpfully suggest to do so. I am guessing this is some sort of hidden session conflict, though? (some googling suggests maybe Mac OS problem related to SSL version?)

```
Error in fb_insights() : 
  This is a bug in the fbRads package. Please report on GitHub with a detailed output: SSL: CA certificate set, but certificate verification is disabled
In addition: Warning message:
In curlSetOpt(..., .opts = .opts, curl = h, .encoding = .encoding) :
  Error setting the option for # 2 (status = 4) (enum = 10097) (value = 0x102a17500): A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision. <not set>
```

This will reliably reproduce the problem on my machine:

```
library(fbRads)
library(RGoogleAnalytics)

fbad_init(fb_account_id, fb_token)

fb_dat <- fb_insights() # issue is the same regardless of fb_insights() value

ga_token <- RGoogleAnalytics::Auth(GA_client_id, GA_client_secret)

RGoogleAnalytics::Validate(ga_token)

ga_query_list <- RGoogleAnalytics::Init(
  start.date  = "2016-08-08",
  end.date    = "2016-08-08",
  dimensions  = _ga_dimens_, # whatever, doesn't seem to matter
  metrics     = _ga_metrics_, # whatever, doesn't seem to matter
  max.results = 10000,
  table.id    = paste0("ga:", as.numeric(ga_id)) # entity id for the GA view
)

ga_query <- RGoogleAnalytics::QueryBuilder(ga_query_list)
ga_dat <- RGoogleAnalytics::GetReportData(ga_query, ga_token)

fb_dat2 <- fb_insights()
```

and sessionInfo():

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin15.5.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RGoogleAnalytics_0.1.1 httr_1.2.1             lubridate_1.5.6       
[4] fbRads_0.2            

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6          digest_0.6.10        bitops_1.0-6        
 [4] R6_2.1.2             chron_2.3-47         plyr_1.8.4          
 [7] jsonlite_1.0         futile.options_1.0.0 magrittr_1.5        
[10] stringi_1.1.1        curl_1.1             data.table_1.9.6    
[13] futile.logger_1.4.3  lambda.r_1.1.9       tools_3.3.1         
[16] stringr_1.0.0        bit64_0.9-5          RCurl_1.95-4.8      
[19] bit_1.1-12           openssl_0.9.4   
```
