### ISSUE TITLE
Facebook Marketing API v2.9

### ISSUE THREAD

**Issue by daroczig** [daroczig/fbRads#52]
https://developers.facebook.com/ads/blog/post/2017/04/18/marketing-API-2.9/

**Comment by zstaykova** [comment]
Hi, do you have any status on this issue?

**Comment by daroczig** [comment]
I've been using the package with manually provided `version = '2.9'` in the `fbad_init` calls for a while now without any problems, so feel free to do the same and I will bump the default version in the package soon too.

**Comment by phlogisticfugu** [comment]
Re: https://developers.facebook.com/docs/apps/changelog

Noting that 2.8 is about to be disabled next week (July 26th)
and that 2.10 is now out.

**Comment by daroczig** [comment]
Yeah, thanks for the reminder @phlogisticfugu -- updated the default version to 2.9 in the package and opened #65.
