### ISSUE TITLE
Error in fbad_request: cannot coerce type 'environment' to vector of type 'character' 

### ISSUE THREAD

**Issue by andrewmccoolCNE** [daroczig/fbRads#58]
I'm getting the following error, which let me know to report on GitHub below. I've tried the same command with v2.9 with the same result, do you have any suggestions here? Thanks!

``` 
> fbacc <- fbad_init(accountid = ###,
...                            token = tkn,
...                            version = '2.8')
ERROR [2017-05-09 08:24:55] URL:  https://graph.facebook.com/v2.8/act_###/
ERROR [2017-05-09 08:24:55] Method:  GET
ERROR [2017-05-09 08:24:55] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,balance,end_advertiser,funding_source,spend_cap,timezone_id,users"
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  This is a bug in the fbRads package. Please report on GitHub with a detailed output: cannot coerce type 'environment' to vector of type 'character' 
```

**Comment by daroczig** [comment]
Can you please share your session info or `devtools::session_info()` would be even better.

**Comment by PK1621** [comment]
Hi Andrew,

I guess your token is not a character but an environment as the error says. Try extracting the token from the environment. (with $credentials)

Philipp

**Comment by daroczig** [comment]
Good catch, @PK1621, thanks for pointing that out. Based on that, I'm closing this comment, please reopen if you think that's still an issue in the package.
