### ISSUE TITLE
Problem Initializing Facebook Account with OAuth token (fbad_init)

### ISSUE THREAD

**Issue by PK1621** [daroczig/fbRads#59]
I receive the following error (fid is my app ID and tok is my token). I replaced all private information such as ID with 'X's. 
Is this due to version incompatibility (2.5 in fbRads while API is 2.9) or am I doing some mistake? 
I double checked wheter I used an appropriate ID. Thus, the error message is confusing. 

```
> fbacc<-fbad_init(fid,tok,version="2.9")
ERROR [2017-05-10 16:50:35] URL:  https://graph.facebook.com/v2.9/act_XXXXX/
ERROR [2017-05-10 16:50:35] Method:  GET
ERROR [2017-05-10 16:50:35] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,balance,capabilities,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2017-05-10 16:50:35] Header: {"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"Invalid parameter\""],"Access-Control-Allow-Origin":["*"],"Pragma":["no-cache"],"Cache-Control":["no-store"],"x-fb-rev":["XXXXX"],"Content-Type":["application/json; charset=UTF-8"],"x-fb-trace-id":["XXXXX"],"facebook-api-version":["v2.9"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"Vary":["Accept-Encoding"],"X-FB-Debug":["XXXXXX+CQ=="],"Date":["Wed, 10 May 2017 14:50:35 GMT"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2017-05-10 16:50:35] Body: {"error":{"message":"Invalid parameter","type":"OAuthException","code":100,"error_subcode":1487168,"is_transient":false,"error_user_title":"The account is invalid","error_user_msg":"The account is invalid","fbtrace_id":"XXXXX"}}

Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  Invalid parameter
```

I hope somebody can help me track down my problem.

Thank you.

**Comment by daroczig** [comment]
The most recent version of fbRads defaults to 2.8 -- I think you are still using the CRAN version, please update to the GitHub version, which works fine with v2.9, at least I've not found any major issues.

**Comment by PK1621** [comment]
Worked out. Thank you!

**Comment by eviling** [comment]
Hi

I installed the GitHub version using
 
 `devtools::install_github("cardcorp/fbRads")`

But I get the same error (me$id is the ID I get using RFACEBOOK package)
`> fbad_init(me$id, tkn, version = "2.9")
ERROR [2017-05-16 14:33:19] URL:  https://graph.facebook.com/v2.9/act_xxx/
ERROR [2017-05-16 14:33:19] Method:  GET
ERROR [2017-05-16 14:33:19] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,balance,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2017-05-16 14:33:19] Header: {"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"Invalid parameter\""],"Access-Control-Allow-Origin":["*"],"Pragma":["no-cache"],"Cache-Control":["no-store"],"x-fb-rev":["XXX"],"Content-Type":["application/json; charset=UTF-8"],"x-fb-trace-id":["XXX"],"facebook-api-version":["v2.9"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"Vary":["Accept-Encoding"],"X-FB-Debug":["XXX+XXX+XX=="],"Date":["Tue, 16 May 2017 12:33:19 GMT"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2017-05-16 14:33:19] Body: {"error":{"message":"Invalid parameter","type":"OAuthException","code":100,"error_subcode":1487168,"is_transient":false,"error_user_title":"The account is invalid","error_user_msg":"The account is invalid","fbtrace_id":"D5UXT5nnBfq"}}
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  Invalid parameter`

Please help me

**Comment by daroczig** [comment]
@eviling can you please confirm that you are using the **Ad** Account ID?

**Comment by eviling** [comment]
I was using the wrong account. It worked

Thanks!!!!

**Comment by zstaykova** [comment]
Hi,
I am having a similar issue, but I am sure I am an admin of both, the page and the ads account. The strange thing is it worked yesterday and today I have the following error:
`ERROR [2017-05-31 13:03:25] URL:  https://graph.facebook.com/v2.9/act_xxx/
ERROR [2017-05-31 13:03:25] Method:  GET
ERROR [2017-05-31 13:03:25] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,balance,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2017-05-31 13:03:25] Header: {"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"(#273) This Ads API call requires the user to be admin of the ad account. User is not admin on ad account xxx.\""],"Access-Control-Allow-Origin":["*"],"Pragma":["no-cache"],"Cache-Control":["no-store"],"x-fb-rev":["3054103"],"Content-Type":["application/json; charset=UTF-8"],"x-fb-trace-id":["CgqmlxLRVoq"],"facebook-api-version":["v2.9"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"Vary":["Accept-Encoding"],"X-FB-Debug":["nO02dBJ7UEPXoucELbtNYxc7ESwueHG+puFfVmKWG7yZr9NiVzgzEYgCn1JvXZ3sAYpc8Cagd8drzrjnTwJBVw=="],"Date":["Wed, 31 May 2017 12:03:25 GMT"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2017-05-31 13:03:25] Body: {"error":{"message":"(#273) This Ads API call requires the user to be admin of the ad account. User is not admin on ad account 1613744825595025.","type":"OAuthException","code":273,"fbtrace_id":"CgqmlxLRVoq"}}
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  (#273) This Ads API call requires the user to be admin of the ad account. User is not admin on ad account xxx.`

I'd appreciate any help!

**Comment by zstaykova** [comment]
I got it all sorted, turned out it was an internal issue. This might be an useful link, where you can test your token https://developers.facebook.com/tools/debug/accesstoken

**Comment by daroczig** [comment]
Dev version of the package resolves the original problem described in this ticket, so closing
