### ISSUE TITLE
Unknown error in fb_insights()

### ISSUE THREAD

**Issue by tokumotion** [daroczig/fbRads#6]
Ran the `fb_insights()` function without arguments and got this error:

```
> fb_insights()
 ERROR [2016-01-28 12:03:09] This is a temporary  FB error.
 INFO [2016-01-28 12:03:11] Retrying query for the 1  st/nd/rd time
 ERROR [2016-01-28 12:03:42] This is a temporary  FB error.
 INFO [2016-01-28 12:03:44] Retrying query for the 2  st/nd/rd time
 ERROR [2016-01-28 12:04:15] This is a temporary  FB error.
 INFO [2016-01-28 12:04:17] Retrying query for the 3  st/nd/rd time
 ERROR [2016-01-28 12:04:49] This is a temporary  FB error.
 Error in fb_insights() : An unknown error occurred
```

The account I got the token from works with API v.2.4. Might that be the problem?

**UPDATE**

The error was on my end. Closing this.

**Comment by daroczig** [comment]
Unfortunately, this happens from time to time  when the FB API has temporary errors.

**Comment by lucasdedavid** [comment]
Is this happening with someone else right now? I'm having this issue for a few days now.
