### ISSUE TITLE
Getting only 25 data rows with fb_insights

### ISSUE THREAD

**Issue by thomiko** [daroczig/fbRads#66]
There is one problem I have been experiencing all the time with the fb_insights function. Every time I retrieve Insights with the fb_insights function (on the campaign level), I get a maximum of 25 result rows, even if there should be definitely more result rows. 

Can there be any quota restrictions on Facebook’s side?

This is the way I authenticate:

```r
app <- oauth_app('facebook', '1234567890', ...)
tkn <- readRDS(paste(path_scripts, "facebook_token.rds", sep = ""))
fbad_init(accountid = id, token = tkn, version = '2.10')
```

This is the insights request:

```r
list_insights <- fb_insights(time_range = '{"since":"2017-07-20","until":"2017-08-08"}', time_increment= 1, 
                            level = 'campaign', 
                            fields = toJSON(c('campaign_name', 'impressions', 'total_actions', 'clicks',
                                               'inline_link_clicks', 'outbound_clicks', 'call_to_action_clicks',
                                               'social_clicks', 'unique_clicks', 'unique_inline_link_clicks',
                                               'unique_outbound_clicks', 'unique_social_clicks', 'spend')))
```

Everything works fine except from the fact that I only get 25 data rows.

After receiving the result from the Facebook API, the “list_insights” list has a data.frame with 25 rows as first element and an empty second element (NULL).

**Comment by daroczig** [comment]
The `fbRads` package does not limit the number of returned rows -- it will also do the pagination automatically if required. I'm actively using this feature to fetch hundreds and thousands of rows in a query -- so not sure what might be the problem.

Can you try to run `debugonce(fb_insights)` before your command and check the data loaded by running the function line by line? Eg check the JSON returned by Facebook and check if that includes more rows etc. Please let me know what you find.

**Comment by thomiko** [comment]
Thanks for the suggestions! Sorry for the late reply, still on holidays :-)
The problem seems to be related to the version of fbRads installed on the respective computer. On the work computer we still have R version 3.2.2 installed (due to compatibility reasons) but I had already upgraded to the latest version of fbRads (2.9.0) via 

devtools::install_github('daroczig/fbRads')

On the work computer where all the previously described problems cropped up, I now even get authentication errors:

ERROR [2017-08-21 11:00:43] Body: {"error":{"message":"(#100) Tried accessing nonexisting field (campaign_name) on node type (URL)","type":"OAuthException","code":100,"fbtrace_id":"XXXXXXXX"}}
Error in fbad_request(path = url$path, method = "GET", params = url$params) : 
  (#100) Tried accessing nonexisting field (campaign_name) on node type (URL)


On my notebook computer I recently upgraded R to the latest versions (3.4.1) but still had an older version of fbRads installed -> v 0.2

With that version 0.2 it worked this morning without any problems. I got the expected 65 data rows spread over 3 elements of the list_insights list (25, 25 and 15 rows). 
 
Now I just updated the fbRads version on my notebook computer to version 2.9.0 (via install_github) and I get exactly the same authetication error message as on my work computer.


I don't know what should be wrong about the field "campaign_name":
https://developers.facebook.com/docs/marketing-api/insights/fields/v2.10

Do I have to change anything in the authentication or the fb_insights calls?

This is how I authenticate for a certain account:
fbad_init(accountid = '1234567890', token = tkn, version = '2.10')

This is the only feedback I get:
TRACE [2017-08-21 11:10:49] Initializing connection to account 1234567890 via API v2.10

**Comment by thomiko** [comment]
If I remove the package but then reinstall it not via install_github but via the RStudio installer (thus installing v0.2) it again works without problems. 

I only get the following warnings:

> fbad_init(accountid = '1234567890', token = tkn, version = '2.10')
Warning messages:
1: In fbad_init(accountid = "1234567890", token = tkn, version = "2.10") :
  FB Graph API v2.4 to be deprecated in a few days! Change to v2.5 ASAP.
2: In fbad_init(accountid = "1234567890", token = tkn, version = "2.10") :
  FB Graph API v2.3 and previous versions are deprecated now.

**Comment by daroczig** [comment]
Can you double check that account id?
The `Tried accessing nonexisting field (campaign_name) on node type (URL)` error message suggests that something is wrong with it, which is also insync with the auth error symptom. 

Try the API explorer at https://developers.facebook.com/tools/explorer for the given ID.

**Comment by thomiko** [comment]
So far I've hardly used the Graph API Explorer. Can you please explain which concrete call I should make and which result should come up if everything's fine there? If I put the account id in the GET input line, I get an authentication error but I don't know if that makes any sense with all the other default settings ...

![graph api explorer](https://user-images.githubusercontent.com/16490122/29533173-f69e5108-86b0-11e7-80ab-0a43935542d9.png)

Why does the fb_insights request work perfectly with the same account id with v0.2 of fbRads?

**Comment by thomiko** [comment]
Does the app require any rights other than those?

![app rights](https://user-images.githubusercontent.com/16490122/29533479-603ec74a-86b2-11e7-9006-695f8a6d1bc1.png)

It seems to me that the read_insights function is only necessary if I want to create an app for other people which they will use "visually":

![read_insights](https://user-images.githubusercontent.com/16490122/29533612-efb77318-86b2-11e7-9456-540e0a05e10b.png)

Is this correct?

**Comment by thomiko** [comment]
Btw: fbad_list_campaign and fbad_read_campaign, for example, work without any problems with that account id and v2.9.0 of fbRads.

**Comment by daroczig** [comment]
As per the original command, you are not passing any `id` to the `fb_insights` command, right? It's picked up automatically as the FB account you used in init. But the above error message suggests that you passed some ids, where the requested fields did not make sense.

Can you pls share the actual command that's causing the problem and the related error message again to simplify debugging? I did not have any luck replicating the problem so far based on the info I received.

**Comment by thomiko** [comment]
Thanks for your feedback! I did more testing and made some interesting observations ;-)

Here's basically how I make the whole call to the fb_insights function:

![fbrads_1](https://user-images.githubusercontent.com/16490122/29742336-955ba596-8a7d-11e7-921a-09ab3b80e6ee.png)

This call fails all the time, even if I set the account or the account path explicitly: 

![fbrads_2](https://user-images.githubusercontent.com/16490122/29742337-9e5ab4ca-8a7d-11e7-85cf-c18da7aec7ba.png)

![fbrads_3](https://user-images.githubusercontent.com/16490122/29742340-a3d1d15e-8a7d-11e7-8be0-6a03bdcc735c.png)


The result is always the same:

![fbrads_4](https://user-images.githubusercontent.com/16490122/29742343-ba312954-8a7d-11e7-92bf-d273bb0de9ea.png)

Please note that the call to the fbad_list_campaign functions directly afterwards always works flawlessy.

So I further inspected what happens inside fb_insights with debugonce as suggested by you earlier. Here's the spot where - after hitting "Next" - fb_insights always fails with the error message shown above:

![fbrads_5](https://user-images.githubusercontent.com/16490122/29742371-5ac5f426-8a7e-11e7-9a4f-0e1b8ca53f9c.png)

Is there any problem with the paging?


Further inspecting the error feedback, I noticed that there is an implicit "limit" parameter:

![fbrads_6](https://user-images.githubusercontent.com/16490122/29742383-8d5a27f4-8a7e-11e7-9bdb-bc04ac058c93.png)

If I explicitly set the "limit" parameter to a number being high enough to get all the expected data rows (no matter if using the implicit ad account id or setting the account or the account path explicitly - as shown above) ...

![fbrads_7](https://user-images.githubusercontent.com/16490122/29742393-c6585418-8a7e-11e7-8800-4f3364f58ec3.png)

... it works without any problems, reporting back all the data rows in one list element!

![fbrads_8](https://user-images.githubusercontent.com/16490122/29742406-11165338-8a7f-11e7-8811-6803b69c915d.png)

**Comment by daroczig** [comment]
I think I bumped into this issue accidentally and could reproduce the problem after all -- should be fixed at 0ad4ed39ab79957c71f1e3b1ca272e1dc0f2296a

**Comment by thomiko** [comment]
Works great, thanks a lot!

**Comment by jayruffell** [comment]
Just came across the same issue of only getting 25 rows of data back from fb_insights calls, using latest version of the package on github (2.10.0).

@thomiko's suggestion of manually setting the limit within the fb_insights call to a large number is working though -  e.g. fb_insights(limit=500, ....).
