### ISSUE TITLE
Improvement: use getInsights() for longer periods of time

### ISSUE THREAD

**Issue by tokumotion** [daroczig/fbRads#7]
When I use `getInsights()`, there is a limit to the ammount of data I can pull from Marketing API, so I have to look at the date of the last output and start from that. Maybe, there should be an function parameter that allows you to make Marketing API further petitions in order to get the whole dataset you're looking to analyze.

**Comment by daroczig** [comment]
You mean the `fb_insights` function? As this can do async queries as well, there shouldn't be a limit on the amount of data to be pulled from the Marketing API. How many ads and what time period are you pulling?

**Comment by tokumotion** [comment]
@daroczig I am pulling 30ish campaigns for the lapse of a year. Each campaign should have around 3 ads each.

**Comment by daroczig** [comment]
Can you post here a demo function call when you hit the limit and the response from FB? Of course please sanitize the account id, token etc.

**Comment by tokumotion** [comment]
Hi @daroczig, this is my example.

```
fblista <- fbad_list_campaign(fields = c("id", "name", "objective", 
                                         "start_time","stop_time"))

fblista %<>%
  filter(grepl("brand1|brand2|brand3", fblista$name, 
               ignore.case = TRUE),
         start_time >= "2015-01-01", stop_time <= "2015-12-31")

fblista[,c(4:5)] <- lapply(fblista[,c(4:5)], ymd_hms)

POST_ENGAGEMENT <- filter(fblista, objective == "POST_ENGAGEMENT")
```

How does POST_ENGAGEMENT look like?

```
> dim(POST_ENGAGEMENT)
[1] 56  5
```

This is where I find some troubles, if I go with `job_type = "async"`:

```
> fb_insights(target = POST_ENGAGEMENT$id,
 +             fields = c("impressions", "social_impressions", "clicks", 
 +                        "social_clicks", "spend", "website_clicks",
 +                        "reach", "ctr", "unique_ctr", "cpc", "cpm",
 +                        "cpp"), job_type = c("async"))
```

I get this error:

```
 Error in fb_insights(target = POST_ENGAGEMENT$id, fields = c("impressions",  : 
  Batched queries are not possible with async call. Please query only one item at a time.
```

If I go with `job_type=c("sync")`

```
> test <– fb_insights(target = POST_ENGAGEMENT$id,
 +             fields = c("impressions", "social_impressions", "clicks", 
 +                        "social_clicks", "spend", "website_clicks",
 +                        "reach", "ctr", "unique_ctr", "cpc", "cpm",
 +                        "cpp"), job_type = c("sync"))
```

I don't get all the data I made a query for (`dim()` should be returning 56 rows):

```
> dim(test$`0`)
[1]  4 14
```

**Comment by daroczig** [comment]
What about querying all your campaigns in your FB account for a time period (using eg `date_preset` or date ranges) instead of passing a list of campaign ids (by omitting the `target` parameter)? That should work with the async methods as well.

Another option could be doing separate queries, something like:

``` r
lapply(POST_ENGAGEMENT$id,
       function(id)
       fb_insights(target = id,
                   fields = c("impressions", "social_impressions", "clicks",
                              "social_clicks", "spend", "website_clicks",
                              "reach", "ctr", "unique_ctr", "cpc", "cpm",
                              "cpp"), job_type = "async"))
```

Then calling `rbindlist` from `data.table` or similar on the results.

**Comment by tokumotion** [comment]
I'm getting this:

```
test_2 <- lapply(POST_ENGAGEMENT$id,
   function(id) fb_insights(target = id,
                 fields = toJSON(c("impressions", "social_impressions", 
                            "clicks",
                            "social_clicks", "spend", "website_clicks",
                            "reach", "ctr", "unique_ctr", "cpc", "cpm",
                            "cpp"), job_type = "async")))
```

This is returns a list with each campaign's insights.

Note that the original code would return error if you don't convert the fields `toJSON()`.

**Comment by daroczig** [comment]
So it works, @tokumotion? If you have the `list`, you should be able to merge those together via `rbindlist` from `data.table` or `do.call` and `rbind`, right?

**Comment by tokumotion** [comment]
@daroczig Yes, it works. I'm currently working on a way to convert the results into a data frame. Thank you!

This code converts the outcome into a dataframe:

```
test_2 <- do.call("rbind", lapply(test_2, data.frame))
```

There is something I don't quite get, if you see the code I placed, the `toJSON()` function encloses the `job_type = "async"`parameter. Running this code will return the desired outcome. However, if you let `job_type="async"` out (as one would intuitively would), the code returns this error:

```
> test_2 <- lapply(POST_ENGAGEMENT$id,
+        function(id) fb_insights(target = id, 
+                                 fields = toJSON(c("impressions", 
+                                                   "social_impressions", 
+                                                   "clicks", "social_clicks", 
+                                                   "spend", "website_clicks",
+                                                   "reach", "ctr", 
+                                                   "unique_ctr", "cpc", 
+                                                   "cpm", "cpp")), 
+                                 job_type = "async"))
```

Error:

```
Error: Argument 'txt' must be a JSON string, URL or file.
Called from: base::stop(..., call. = FALSE)
```

Why would you have to insert `job_type="async"`into the JSON file?

**Comment by daroczig** [comment]
Sounds good, thanks for the feedback -- I am closing this ticket. Can you please open a new ticket for the `job_type` issue with a minimal example?
