### ISSUE TITLE
Facebook Conversions

### ISSUE THREAD

**Issue by eviling** [daroczig/fbRads#70]
Hello,

I am using fb_insights from fbRads and I need to get facebook conversions. 
Do you know how can I get it? is there a field for this in Facebook Insights?

This conversions should be equivalent to google adwords conversions.

Thanks

**Comment by daroczig** [comment]
Yeah, check the related docs at https://developers.facebook.com/docs/marketing-api/insights/fields -- I think you want `actions`, which lists all the `offsite_conversion` events as per https://developers.facebook.com/docs/marketing-api/reference/ads-action-stats/

**Comment by eviling** [comment]
Thanks, you were right, but how can I do if I want from the field actions only the offsite_conversion. How can I gest it?. 
I am doing it:

`fb_insights(fbacc, time_range = paste0("{'since':'",startdate,"','until':'",enddate,"'}"),
                            time_increment = 1, level = 'ad', fields = "['date_start',
                            'date_stop','campaign_name','impressions','spend','clicks','cpc','reach',
                            'actions','offsite_conversion']")
`
And I get this error: Error: Argument 'txt' must be a JSON string, URL or file.

**Comment by daroczig** [comment]
As per the above referenced FB docs, `offsite_conversion` is not a valid field. Query `actions` and extract the required subfields from there. I've just pushed an update to `fbRads` to return the API error msg at b477c4c
