### ISSUE TITLE
Lexical error when retrieving campaign data

### ISSUE THREAD

**Issue by diegocgaona** [daroczig/fbRads#71]
Hi,

First, thanks for the great package.

I received a error when trying to get some campaign data, the error occur because the campaign name have portuguese accentuation (Agronegócios).
I changed the campaign name in Facebook Ads and it work fine now, and it's odd, because I have many other campaigns with accentuation and no error.

I thought would be best to report the error, maybe others could have the same problem.

I'm using the fbRads 2.9.0 and Microsoft R Open 3.4.1

```
l <- fb_insights(date_preset = 'last_month', level = 'campaign', fields = toJSON(c('campaign_name','objective', 'unique_actions','spend','clicks','ctr','reach','cpc','cpm','total_actions','impressions')))
Error: lexical error: invalid character inside string.
          ame":"Encontros - AgronegÃ³cio e mercado de capitais - 01-09
                     (right here) ------^
```

Many thanks, Diego.

**Comment by daroczig** [comment]
Hey Diego, can you please share your `devtools::session_info()`, especially the locale? Also, running `debugonce(fb_insights)` before the above command, then pressing enter until the fn evaluates the `res <- tryCatch(fbad_request ...` line -- can you please check / paste here the JSON returned by FB? Feel free to remove sensitive information from the JSON, I'm mainly interested in seeing a malformed JSON returned by FB and then I can start thinking how to fix that (like we do with the unescaped line breaks).

**Comment by diegocgaona** [comment]
Well... after I changed the name of the campaign, it worked. I tried to change back, but still works... 

I sending my session info, but, I think the problem is solved, maybe a temporary error only.

My session info:

```
Session info -------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.0.153)           
 language (EN)                        
 collate  Portuguese_Brazil.1252      
 tz       America/Sao_Paulo           
 date     2017-10-02                  

```
I think it's solved, if it happen again, I will do the debugs how you said.

Many thanks!

**Comment by daroczig** [comment]
Thanks for the promp feedback. Let me close this ticket then, pls do reopen if you see this problem again.
