### ISSUE TITLE
Error in fbad_request - name lookup timed out

### ISSUE THREAD

**Issue by daap86** [daroczig/fbRads#73]
Hi,

When I execute my code in R Server, I get the following error after this line: 

> fbacc=fbad_init(accid,tkn,version="2.10")
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : This is a bug in the fbRads package. Please report on GitHub with a detailed output: name lookup timed out

However, when I execute it in my computer it works fine, whether loading the token from .rds file or obtaining it from credentials.

Thanks in advance for your help.

**Comment by poplavok** [comment]
Similar issue, but executing in Rstudio I am doing this from work through the guest network.  WIll try this at home and update if there is a difference.

> fbad_init(accountid = acc_id2, token=tkn, version = '2.5')
TRACE [2017-12-05 17:26:38] Initializing connection to account 10151637457570059 via API v2.5
ERROR [2017-12-05 17:26:38] URL:  https://graph.facebook.com/v2.5/act_10151637457570059/
ERROR [2017-12-05 17:26:38] Method:  GET
ERROR [2017-12-05 17:26:38] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,end_advertiser,funding_source,spend_cap,timezone_id,users"
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  This is a bug in the fbRads package. Please report on GitHub with a detailed output: cannot coerce type 'environment' to vector of type 'character

Session info:

>  package        * version  date       source                          
 base           * 3.4.2    2017-10-27 local                           
 bit              1.1-12   2014-04-09 CRAN (R 3.4.2)                  
 bit64            0.9-7    2017-05-08 CRAN (R 3.4.2)                  
 bitops           1.0-6    2013-08-17 CRAN (R 3.4.2)                  
 compiler         3.4.2    2017-10-27 local                           
 curl             3.0      2017-10-06 CRAN (R 3.4.2)                  
 data.table       1.10.4-3 2017-10-27 CRAN (R 3.4.2)                  
 datasets       * 3.4.2    2017-10-27 local                           
 devtools         1.13.4   2017-11-09 CRAN (R 3.4.2)                  
 digest           0.6.12   2017-01-27 cran (@0.6.12)                  
 fbRads         * 2.10.0   2017-12-05 Github (daroczig/fbRads@90a774b)
 futile.logger    1.4.3    2016-07-10 CRAN (R 3.4.2)                  
 futile.options   1.0.0    2010-04-06 CRAN (R 3.4.2)                  
 git2r            0.19.0   2017-07-19 CRAN (R 3.4.2)                  
 graphics       * 3.4.2    2017-10-27 local                           
 grDevices      * 3.4.2    2017-10-27 local                           
 httpuv         * 1.3.5    2017-07-04 CRAN (R 3.4.2)                  
 httr           * 1.3.1    2017-08-20 CRAN (R 3.4.2)                  
 jsonlite         1.5      2017-06-01 cran (@1.5)                     
 lambda.r         1.2      2017-09-16 CRAN (R 3.4.2)                  
 memoise          1.1.0    2017-04-21 CRAN (R 3.4.2)                  
 methods        * 3.4.2    2017-10-27 local                           
 plyr             1.8.4    2016-06-08 cran (@1.8.4)                   
 R6               2.2.2    2017-06-17 cran (@2.2.2)                   
 Rcpp             0.12.14  2017-11-23 cran (@0.12.14)                 
 RCurl            1.95-4.8 2016-03-01 CRAN (R 3.4.2)                  
 Rfacebook      * 0.6.15   2017-05-25 CRAN (R 3.4.2)                  
 rjson          * 0.2.15   2014-11-03 CRAN (R 3.4.2)                  
 rstudioapi       0.7      2017-09-07 CRAN (R 3.4.2)                  
 stats          * 3.4.2    2017-10-27 local                           
 tools            3.4.2    2017-10-27 local                           
 utils          * 3.4.2    2017-10-27 local                           
 withr            2.1.0    2017-11-01 CRAN (R 3.4.2)                  
 yaml             2.1.14   2016-11-12 CRAN (R 3.4.2)

**Comment by poplavok** [comment]
just learned that FB api has had issues all day. Will try tomorrow if issue persists

**Comment by daroczig** [comment]
Seems to be a temp network issues - please reopen if the problem persists

**Comment by daap86** [comment]
Hi, I think you should reopen this issue (I can't do it), because I don't think this is a temporal problem. I've been getting this error since last Friday in R Server, but not in my computer. Also the error mentioned by @poplavok is not exactly the same ("cannot coerce type 'environment' to vector of type 'character'").

**Comment by daroczig** [comment]
@daap86 see the error message from your post: `name lookup timed out` -- that's a network issue that we cannot resolve within the R package. Check the network settings (eg DNS) of your server.
