### ISSUE TITLE
fbad_init invalid token

### ISSUE THREAD

**Issue by poplavok** [daroczig/fbRads#74]
Having issues with token authorization full code

```
> `pp<-oauth_app("facebook", app_id, app_secret)
Sys.setenv('httr_server_port' = '1410/')
tkn <- oauth2.0_token(
  oauth_endpoints('facebook'), app, scope = 'public_profile',
  type = 'application/x-www-form-urlencoded', cache = FALSE)
tkn <- jsonlite::fromJSON(names(tkn$credentials))
saveRDS(tkn, "fb-oauth.rds")
fb_tkn <- readRDS("fb-oauth.rds")
fb_tkn
fbad_init(accountid = acc_id, token=fb_tkn, version = '2.10')`
```

Error message 

```
> fbad_init(accountid = acc_id, token=fb_tkn, version = '2.10')
TRACE [2017-12-06 11:15:33] Initializing connection to account 10155883602248117 via API v2.10
ERROR [2017-12-06 11:15:33] URL:  https://graph.facebook.com/v2.10/act_10155883602248117/
ERROR [2017-12-06 11:15:33] Method:  GET
ERROR [2017-12-06 11:15:33] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2017-12-06 11:15:33] Header: {"Access-Control-Allow-Origin":["*"],"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_token\" \"Invalid OAuth access token.\""],"Pragma":["no-cache"],"Cache-Control":["no-store"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"x-fb-rev":["3504978"],"Content-Type":["application/json; charset=UTF-8"],"x-fb-trace-id":["Ei0ogx/rZAH"],"Strict-Transport-Security":["max-age=15552000; preload"],"X-FB-Debug":["El7CmyGjAryeXwm0OjsPtfMUVIJRhv4AlHnBoVwulYnhHMZc/wfZ8h5YnddVzX9LHy3kCtDSdB32E88ulC0GQg=="],"Date":["Wed, 06 Dec 2017 16:15:34 GMT"],"Connection":["keep-alive"],"Content-Length":["114"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2017-12-06 11:15:33] Body: {"error":{"message":"Invalid OAuth access token.","type":"OAuthException","code":190,"fbtrace_id":"Ei0ogx\/rZAH"}}
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  Invalid OAuth access token.
```

I have checked the access token here [https://developers.facebook.com/tools/debug/accesstoken](url)
and the token is valid. 

Any ideas and/or help would be greatly appreciated.

**Comment by daroczig** [comment]
After parsing the JSON, I don't see that you are extracting the `access_token` as described at https://github.com/daroczig/fbRads#creating-a-facebook-app--connect-with-oauth-token -- can you pls check again?

**Comment by poplavok** [comment]
Thanks for the quick response, that didn't work yesterday but worked today. I am experiencing a different error at this point, in the interest of not opening a fresh request just want to confirm

> Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  Unsupported get request.

full text, does that imply an incorrect account id or version error?

>  fbad_init(accountid = acc_id, token=fb_tkn, version = '2.11')
TRACE [2017-12-06 11:32:25] Initializing connection to account 10155883602248117 via API v2.11
ERROR [2017-12-06 11:32:26] URL:  https://graph.facebook.com/v2.11/act_10155883602248117/
ERROR [2017-12-06 11:32:26] Method:  GET
ERROR [2017-12-06 11:32:26] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2017-12-06 11:32:26] Header: {"Strict-Transport-Security":["max-age=15552000; preload"],"x-fb-trace-id":["BZxO8vp/dsm"],"x-fb-rev":["3505243"],"Content-Type":["application/json; charset=UTF-8"],"facebook-api-version":["v2.11"],"Cache-Control":["no-store"],"Pragma":["no-cache"],"Access-Control-Allow-Origin":["*"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"Unsupported get request.\""],"X-FB-Debug":["+ssOFk5Jx9UPM5iWEpWd4dO6i2o+e7+6jt8sTfKzT9HN+7PWwjaXUhFUDsM3NPPj60t5YlGmSVpiuM9VpFb/7Q=="],"Date":["Wed, 06 Dec 2017 16:32:26 GMT"],"Connection":["keep-alive"],"Content-Length":["117"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2017-12-06 11:32:26] Body: {"error":{"message":"Unsupported get request.","type":"GraphMethodException","code":100,"fbtrace_id":"BZxO8vp\/dsm"}}
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  Unsupported get request.
