### ISSUE TITLE
Unsupported Get Request

### ISSUE THREAD

**Issue by poplavok** [daroczig/fbRads#75]
Are there specific app permissions necessary for basic functions described in your tutorial? I have followed instructions and have the basic 3 functionalities that are set up when creating an app, including app permisssions but I get an unsupported get request error. My understanding is that its usually a function of permissions, are you able to comment?

> fbad_init(accountid = acc_id, token=fb_tkn2, version = '2.11')
TRACE [2017-12-06 12:11:20] Initializing connection to account 10155883602248117 via API v2.11
ERROR [2017-12-06 12:11:21] URL:  https://graph.facebook.com/v2.11/act_10155883602248117/
ERROR [2017-12-06 12:11:21] Method:  GET
ERROR [2017-12-06 12:11:21] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2017-12-06 12:11:21] Header: {"Strict-Transport-Security":["max-age=15552000; preload"],"x-fb-trace-id":["G63pilcbjjW"],"x-fb-rev":["3505243"],"Content-Type":["application/json; charset=UTF-8"],"facebook-api-version":["v2.11"],"Cache-Control":["no-store"],"Pragma":["no-cache"],"Access-Control-Allow-Origin":["*"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"Unsupported get request.\""],"X-FB-Debug":["eVr3aWze3gR0mmhUIaYYwV1Ki5leL44czG6hvqo0v0OWdO87H/dDGmQRdimo7QfNxOKU5io1bk250d6PyLBhwg=="],"Date":["Wed, 06 Dec 2017 17:11:21 GMT"],"Connection":["keep-alive"],"Content-Length":["116"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2017-12-06 12:11:21] Body: {"error":{"message":"Unsupported get request.","type":"GraphMethodException","code":100,"fbtrace_id":"G63pilcbjjW"}}
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  Unsupported get request.

**Comment by peeyooshc** [comment]
I had this problem a while back and the answer was to:
* upgrade to the latest version of R or 3.3 at the very least
* Update httr (as some packages install a previous version)

Hope this helps.

**Comment by poplavok** [comment]
Thanks for the effort, but I don't believe that to be an issue. I'm on R 3.4 and here is the session info for the relevant packages

>R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS
 attached base packages:
other attached packages:
[1] fbRads_2.10.0    Rfacebook_0.6.15 httpuv_1.3.5     rjson_0.2.15     httr_1.3.1

**Comment by daroczig** [comment]
Pls double check the Ad Account id -- FB returns this error if you specify a wrong id or you have no permissions to access it. Try the API explorer to make sure you have the right permissions at https://developers.facebook.com/tools/explorer

**Comment by poplavok** [comment]
Thanks daro for being patient. Double checked account id and changed permissions accordingly.  Issue resolved.
