### ISSUE TITLE
Breaking change in version 2.10

### ISSUE THREAD

**Issue by simran66** [daroczig/fbRads#76]
I am using fbRads package and needed to update to version 2.10.

I have these two statements in my import:

fb_listAdd <<- fbad_list_ad(fields = c('id','account_id','adset_id', 'campaign_id', 'configured_status', 'created_time',  'effective_status', 'last_updated_by_app_id', 'name', 'status', 'updated_time'))

and

fb_listCampaign <<- fbad_list_campaign(fields = c('id','account_id', 'buying_type', 'can_use_spend_cap', 'configured_status', 'created_time', 'effective_status', 'name', 'objective', 'spend_cap', 'start_time', 'status', 'updated_time'))

With that, I get this error:

```
ERROR [2017-12-07 19:01:16] URL:  https://graph.facebook.com/v2.10/act_1377538909175363/adgroups
ERROR [2017-12-07 19:01:16] Method:  GET
ERROR [2017-12-07 19:01:17] Params:  List of 2
 $ fields: chr "id,account_id,adset_id,campaign_id,configured_status,created_time,effective_status,last_updated_by_app_id,name,status,updated_t"| __truncated__
 $ limit : num 1000
ERROR [2017-12-07 19:01:17] Header: {"Strict-Transport-Security":["max-age=15552000; preload"],"x-fb-trace-id":["DaXZeSdu2um"],"x-fb-rev":["3508911"],"Content-Type":["application/json; charset=UTF-8"],"facebook-api-version":["v2.10"],"Cache-Control":["no-store"],"Pragma":["no-cache"],"Access-Control-Allow-Origin":["*"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"(#100) Tried accessing nonexisting field (adgroups) on node type (AdAccount)\""],"Vary":["Accept-Encoding"],"X-FB-Debug":["P8YQxbF4NTI4hx6ZAPOQsNibi4adN7/CTefsW6opgg7gXE/g63VRtYtbGD5ivPzrO5W4A5q7Brng9v33nOyLRA=="],"Date":["Thu, 07 Dec 2017 13:31:16 GMT"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2017-12-07 19:01:17] Body: {"error":{"message":"(#100) Tried accessing nonexisting field (adgroups) on node type (AdAccount)","type":"OAuthException","code":100,"fbtrace_id":"DaXZeSdu2um"}}
```

I have checked in the documentation and all of the fields I am asking for here do indeed exist. 

Could you please point out what could be the problem here?

Infact I have tried removing all of the fields and yet I receive the same error

**Comment by daroczig** [comment]
I cannot reproduce this problem after testing on some Ad Accounts, so pls try to provide more detauls, eg provide your `devtools::session_info()` and try on different Ad Acccounts

**Comment by simran66** [comment]
@daroczig 
I have tried it with other AdAccounts:

Ad account Ids currently in use are as follows:

accountIds<- c('1377538909175363', '784298674999592','874355815993877', '880218078740984')


Session Info------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Asia/Kolkata                
 date     2017-12-08                  

Packages --------------------------------------------------------------------------------------------------------------------
 package        * version  date       source                                    
 acepack          1.4.1    2016-10-29 cran (@1.4.1)                             
 assertthat       0.2.0    2017-04-11 cran (@0.2.0)                             
 backports        1.0.5    2017-01-18 cran (@1.0.5)                             
 base           * 3.3.3    2017-03-08 local                                     
 base64enc        0.1-3    2015-07-28 cran (@0.1-3)                             
 bindr            0.1      2016-11-13 cran (@0.1)                               
 bindrcpp         0.2      2017-06-17 cran (@0.2)                               
 bit              1.1-12   2014-04-09 CRAN (R 3.3.3)                            
 bit64            0.9-7    2017-05-08 cran (@0.9-7)                             
 bitops           1.0-6    2013-08-17 CRAN (R 3.3.3)                            
 cellranger       1.1.0    2016-07-27 CRAN (R 3.3.3)                            
 checkmate        1.8.2    2016-11-02 cran (@1.8.2)                             
 cluster          2.0.5    2016-10-08 CRAN (R 3.3.3)                            
 colorspace       1.3-2    2016-12-14 cran (@1.3-2)                             
 curl           * 2.8.1    2017-07-21 cran (@2.8.1)                             
 data.table       1.10.4   2017-02-01 cran (@1.10.4)                            
 datasets       * 3.3.3    2017-03-08 local                                     
 DBI              0.6-1    2017-04-01 cran (@0.6-1)                             
 devtools         1.13.3   2017-08-02 CRAN (R 3.3.3)                            
 digest           0.6.12   2017-01-27 CRAN (R 3.3.3)                            
 dplyr            0.7.4    2017-09-28 cran (@0.7.4)                             
 fbRads         * 0.2      2016-04-06 CRAN (R 3.3.3)                            
 foreign          0.8-67   2016-09-13 CRAN (R 3.3.3)                            
 Formula          1.2-1    2015-04-07 cran (@1.2-1)                             
 futile.logger    1.4.3    2016-07-10 CRAN (R 3.3.3)                            
 futile.options   1.0.0    2010-04-06 CRAN (R 3.3.3)                            
 ggplot2          2.2.1    2016-12-30 cran (@2.2.1)                             
 glue             1.2.0    2017-10-29 cran (@1.2.0)                             
 googlesheets     0.2.2    2017-05-07 CRAN (R 3.3.3)                            
 graphics       * 3.3.3    2017-03-08 local                                     
 grDevices      * 3.3.3    2017-03-08 local                                     
 grid             3.3.3    2017-03-08 local                                     
 gridExtra        2.2.1    2016-02-29 cran (@2.2.1)                             
 gtable           0.2.0    2016-02-26 cran (@0.2.0)                             
 Hmisc            4.0-2    2016-12-31 cran (@4.0-2)                             
 htmlTable        1.9      2017-01-26 cran (@1.9)                               
 htmltools        0.3.6    2017-04-28 cran (@0.3.6)                             
 htmlwidgets      0.9      2017-07-10 CRAN (R 3.3.3)                            
 httpuv         * 1.3.5    2017-07-04 cran (@1.3.5)                             
 httr           * 1.3.1    2017-08-20 cran (@1.3.1)                             
 igraph           1.0.1    2015-06-26 CRAN (R 3.3.3)                            
 instaR           0.2.4    2016-08-17 CRAN (R 3.3.3)                            
 jsonlite         1.5      2017-06-01 cran (@1.5)                               
 knitr            1.17     2017-08-10 cran (@1.17)                              
 lambda.r         1.1.9    2016-07-10 CRAN (R 3.3.3)                            
 lattice          0.20-34  2016-09-06 CRAN (R 3.3.3)                            
 latticeExtra     0.6-28   2016-02-09 cran (@0.6-28)                            
 lazyeval         0.2.0    2016-06-12 cran (@0.2.0)                             
 magrittr         1.5      2014-11-22 CRAN (R 3.3.3)                            
 Matrix           1.2-8    2017-01-20 CRAN (R 3.3.3)                            
 memoise          1.0.0    2016-01-29 CRAN (R 3.3.3)                            
 methods        * 3.3.3    2017-03-08 local                                     
 munsell          0.4.3    2016-02-13 cran (@0.4.3)                             
 NLP              0.1-10   2017-02-21 CRAN (R 3.3.3)                            
 nnet             7.3-12   2016-02-02 CRAN (R 3.3.3)                            
 parallel         3.3.3    2017-03-08 local                                     
 pkgconfig        2.0.1    2017-03-21 cran (@2.0.1)                             
 plyr             1.8.4    2016-06-08 CRAN (R 3.3.3)                            
 purrr            0.2.4    2017-10-18 cran (@0.2.4)                             
 R6               2.2.2    2017-06-17 cran (@2.2.2)                             
 RAdwords       * 0.1.14   2017-10-02 CRAN (R 3.3.3)                            
 RColorBrewer     1.1-2    2014-12-07 cran (@1.1-2)                             
 Rcpp             0.12.13  2017-09-28 cran (@0.12.13)                           
 RCurl            1.95-4.8 2016-03-01 CRAN (R 3.3.3)                            
 Rfacebook      * 0.6.11   2017-01-04 CRAN (R 3.3.3)                            
 rhdfs          * 1.0.8    2017-04-07 Github (RevolutionAnalytics/rhdfs@835d4e5)
 rJava          * 0.9-8    2016-01-07 CRAN (R 3.3.3)                            
 rjson          * 0.2.15   2014-11-03 CRAN (R 3.3.3)                            
 rlang            0.1.2    2017-08-09 cran (@0.1.2)                             
 rlist          * 0.4.6.1  2016-04-04 CRAN (R 3.3.3)                            
 rpart            4.1-10   2015-06-29 CRAN (R 3.3.3)                            
 scales           0.5.0    2017-08-24 cran (@0.5.0)                             
 slam             0.1-40   2016-12-01 CRAN (R 3.3.3)                            
 SocialMediaLab * 0.23.0   2016-07-22 CRAN (R 3.3.3)                            
 splines          3.3.3    2017-03-08 local                                     
 stats          * 3.3.3    2017-03-08 local                                     
 stringi          1.1.5    2017-04-07 cran (@1.1.5)                             
 stringr          1.2.0    2017-02-18 CRAN (R 3.3.3)                            
 survival         2.40-1   2016-10-30 CRAN (R 3.3.3)                            
 tibble           1.3.4    2017-08-22 cran (@1.3.4)                             
 tm               0.7-1    2017-03-02 CRAN (R 3.3.3)                            
 tools            3.3.3    2017-03-08 local                                     
 twitteR          1.1.9    2015-07-29 CRAN (R 3.3.3)                            
 utils          * 3.3.3    2017-03-08 local                                     
 withr            1.0.2    2016-06-20 CRAN (R 3.3.3)

**Comment by daroczig** [comment]
Oh, you are using a very old version of fbRads -- pls update to the dev
version from github

--
Sent from a mobile phone with an annoying input interface, pls excuse my
brevity/spelling issues.

**Comment by simran66** [comment]
Thank you :) Updated and worked
