### ISSUE TITLE
fb_api_most_recent_version

### ISSUE THREAD

**Issue by gandhiu** [daroczig/fbRads#78]
Hi I am using the call for fb_api_most_recent_version and getting back 2.10. 

Facebook Ads API is now at 2.11 with 2.10 being completely deprecated. Is it possible to update this to 2.11 ?

Regards

**Comment by daroczig** [comment]
Not sure why you think 2.10 is deprecated -- it's still available, supported as per https://developers.facebook.com/docs/graph-api/changelog#marketing-api-changelog and I'm also pretty actively using it.

Anyway, 2.10 is only the default version in `fbRads`, but you can use any other version of the Marketing API, see the params of `fbad_init`

**Comment by gandhiu** [comment]
Thanks ! was trying to automate the process so that I don’t have keep a track of FB API changes. Thanks for the package !!! pretty nifty ☺

**Comment by daroczig** [comment]
Will bump the default API version in the next couple weeks after reviewing https://developers.facebook.com/docs/graph-api/changelog/version2.11#mapi

FTR I specify a hardcoded API version in all my R scripts, so that I review all my stuff for API breaking changes before updating the API version

**Comment by gandhiu** [comment]
Thanks so much !!

**Comment by daroczig** [comment]
Will be closed in a couple days at af7fe707952d89036457f6c10737b67c9fff6876
