### ISSUE TITLE
Improvement: Facebook Pixel data collection

### ISSUE THREAD

**Issue by albertabello** [daroczig/fbRads#8]
Hi,

I would like to suggest an improvement:

The ability to fetch data from fb_insights collected by the Facebook and Conversion Pixel.
This tool is amazing for report building also and without this feature it lacks some potential.

What do you think?

BR
Albert

**Comment by daroczig** [comment]
Hello Albert, 

I think looking for `actions` in the `fileds` arguments of `fb_insights` should also return the conversion etc stats. Or can you please describe what other data are you looking for?

**Comment by albertabello** [comment]
Hello,

Yeah I have noticed that data appears there. I've been able to parse it out of the JSON using the following code:

```

# Get last week data
l <- fb_insights(date_preset = 'last_week', level = 'campaign', fields = toJSON(c('campaign_name','spend', 'action_values', 'unique_actions')))
# Expenses 
fb_expenses_w <- sum(l[[1]][,2])
# total sales
fb_sales_w <- 0
i <- 0  
for(i in 1:length(l[[1]][,3]))
{
  if (length(l[[1]][,3][[i]]$value[grep('offsite_conversion.fb_pixel_purchase', l[[1]][,3][[i]]$action_type)]) > 0) {
    print(l[[1]][,3][[i]]$value[grep('offsite_conversion.fb_pixel_purchase', l[[1]][,3][[i]]$action_type)])
    fb_sales_w <- fb_sales_w + l[[1]][,3][[i]]$value[grep('offsite_conversion.fb_pixel_purchase', l[[1]][,3][[i]]$action_type)]
  }
}
# total units sold
fb_units_w <- 0
i <- 0  
for(i in 1:length(l[[1]][,3]))
{
  if (length(l[[1]][,4][[i]]$value[grep('offsite_conversion.fb_pixel_purchase', l[[1]][,4][[i]]$action_type)]) > 0) {
    print(l[[1]][,4][[i]]$value[grep('offsite_conversion.fb_pixel_purchase', l[[1]][,4][[i]]$action_type)])
    fb_units_w <- fb_units_w + l[[1]][,4][[i]]$value[grep('offsite_conversion.fb_pixel_purchase', l[[1]][,4][[i]]$action_type)]
  }
}
```

In case someone needs it i leave it there. It might be a bit hard but meanwhile they do not change the JSON it will work fine.

One more question, how can I select personalized data ranges to fetch the data? Instead of the `yesterday` or `last_week`.

**Comment by albertabello** [comment]
Found it:

`
l <- fb_insights(date_preset = 'last_week', level = 'campaign', fields = toJSON(c('campaign_name','spend', 'action_values', 'unique_actions')), time_range="{'since':'2016-01-01','until':'2016-01-20'}")
`

It would be nice to specify this on the help :) I bet many people finds themselves on the same issue.

Thank you for this awesome library.

**Comment by daroczig** [comment]
Well, processing the returned JSON list can be indeed tricky sometimes :( I was thinking about doing that as part of the package, but as the output of `fb_insights` highly depends on the list of `fields`, it's not easily doable. I use in my scripts the `rlist`package and `rbindlist` from `data.table` a lot, eg:

``` r
rbindlist(lapply(l, function(l) cbind(campaign_name = l$campaign_name, rbindlist(l$unique_actions))))
```

**Comment by albertabello** [comment]
Yeah I have been using that now also but I prefer not to rely too much in libraries and packages. Fetching the data on the account level allows it to be easier to parse and drible the limitation on developer access type.

Thank you!
