### ISSUE TITLE
numbers of columns of arguments do not match

### ISSUE THREAD

**Issue by simran66** [daroczig/fbRads#84]
fb_listAdset <<- fbad_list_adset(fields = c('id','account_id', 'campaign_id', 'configured_status', 'budget_remaining', 'created_time', 'start_time', 'daily_budget', 'effective_status', 'is_autobid', 'updated_time', 'lifetime_budget', 'lifetime_frequency_cap', 'lifetime_imps', 'optimization_goal', 'name'))
On trying to execute above LOC, I get 

Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match`

Suddenly I have been getting this error. Used to work fine so far. What's the issue?

**Comment by daroczig** [comment]
When you are quering complex fields returning lists instead of scalar values, you'll have to use `simplify = FALSE` and do the post-processing on your own
