### ISSUE TITLE
fbad_create_creative and list parameters

### ISSUE THREAD

**Issue by braunm** [daroczig/fbRads#87]
I am trying to create a new creative, whose definition includes an 'object_story_spec'.

```
spec <- list(link_data=list(image_hash=<IMAGE_HASH>, 
    link=<LANDING_PAGE_URL>, 
    message="test message",
    page_id=<PAGE_ID>)
)
```
When I try to create the creative with
```
fbad_create_creative(fbac, title="test title",
   body="test body", name="test name", 
   object_story_spec=spec, object_id=page_id)
```
I get the following error (appropriately redacted):

> ERROR [2018-03-25 20:14:37] URL:  https://graph.facebook.com/v2.12/act_<ACC_ID>/adcreatives
ERROR [2018-03-25 20:14:37] Method:  POST
ERROR [2018-03-25 20:14:37] Params:  List of 5
 $ title            : chr "test title"
 $ body             : chr "test body"
 $ name             : chr "test name"
 $ object_id        : chr "<OBJ_ID>"
 $ object_story_spec:List of 2
  ..$ link_data:List of 3
  .. ..$ image_hash: chr "<IMAGE_HASH>"
  .. ..$ link      : chr "<LANDING_PAGE_URL>
  .. ..$ message   : chr "test message"
  ..$ page_id  : chr "<PAGE_ID>"
Error in fbad_request(fbacc, path = paste0("act_", fbacc$account_id, "/adcreatives"),  : 
  This is a bug in the fbRads package. Please report on GitHub with a detailed output: STRING_ELT() can only be applied to a 'character vector', not a 'list'

I unsuccessfully tried solving this myself by hacking on the `fbad_request` function.  I think the issue is in how fbRads converts nested lists into JSON objects.  I did try including `toJSON(spec)` in the params, but characters in the landing page URL  were escaped in such a way that FB did not recognize the URL as valid.

**Comment by daroczig** [comment]
The `page_id` is defined within the `link_data` in your example `spec`, maybe something like:

```r
spec <- list(
    link_data = list(
        image_hash = 'asd',
        link = 'http://example.cpom',
        message = "test message"),
    page_id = '123456789')
library(jsonlite)
toJSON(spec, auto_unbox = TRUE)
```

Pass that JSON as `object_story_spec` -- let me know how it works

**Comment by braunm** [comment]
Thanks. your solution does work.  For others who may be reading this, the `auto_unbox=TRUE` argument is critical.  Otherwise, backslashes in the url are escaped, leading to a "URL can't be used" error.

However, I can envision cases in which we do not want an argument unboxed (e.g., the API required an array).  `unbox(url)` generates a "field must be a string" error.  So I can use `auto_unbox=TRUE` for now, but I'm not sure that's a stable, long-term solution.

From what I can tell, this all has to do with how `Curl::postForm` handles list elements in lists.  I may experiment with sending the API calls using the httr package instead.


(Note: my `spec` object was correct.  `link_data` and `page_id` are at the same level in the `object_story_spec` list.)
