### ISSUE TITLE
"This is a bug in the fbRads package. Please report on GitHub with a detailed output"

### ISSUE THREAD

**Issue by thomiko** [daroczig/fbRads#89]
This is the detailed output (only replaced IDs with Xs, Ys and Zs):

TRACE [2018-04-10 10:30:03] Initializing connection to account XXXXXXXXXXXXXXXXXX via API v2.10
6 1 
[1] "{\"since\":\"2018-04-04\",\"until\":\"2018-04-09\"}"
DEBUG [2018-04-10 10:30:17] Sync request failed, starting async request.
DEBUG [2018-04-10 10:30:19] YYYYYYYYYYYYYYY Async Job Started (0%). Waiting 2 seconds...
DEBUG [2018-04-10 10:30:21] YYYYYYYYYYYYYYY Async Job Started (0%). Waiting 10 seconds...
12 7 
[1] "{\"since\":\"2018-03-29\",\"until\":\"2018-04-03\"}"
DEBUG [2018-04-10 10:31:42] Sync request failed, starting async request.
DEBUG [2018-04-10 10:31:43] YYYYYYYYYYYYYYY Async Job Not Started (0%). Waiting 2 seconds...
DEBUG [2018-04-10 10:31:45] YYYYYYYYYYYYYYY Async Job Started (0%). Waiting 10 seconds...
18 13 
[1] "{\"since\":\"2018-03-23\",\"until\":\"2018-03-28\"}"
DEBUG [2018-04-10 10:33:06] Sync request failed, starting async request.
DEBUG [2018-04-10 10:33:11] YYYYYYYYYYYYYYY Async Job Started (0%). Waiting 2 seconds...
DEBUG [2018-04-10 10:33:15] YYYYYYYYYYYYYYY Async Job Started (0%). Waiting 10 seconds...
ERROR [2018-04-10 10:34:12] Possible network error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received
INFO [2018-04-10 10:34:12] Retrying query for the 1  st/nd/rd time
24 19 
[1] "{\"since\":\"2018-03-17\",\"until\":\"2018-03-22\"}"
DEBUG [2018-04-10 10:35:31] Sync request failed, starting async request.
DEBUG [2018-04-10 10:35:38] YYYYYYYYYYYYYYY Async Job Started (0%). Waiting 2 seconds...
DEBUG [2018-04-10 10:35:41] YYYYYYYYYYYYYYY Async Job Started (0%). Waiting 10 seconds...
ERROR [2018-04-10 10:36:05] Possible network error: Connection timed out after 3011 milliseconds
INFO [2018-04-10 10:36:05] Retrying query for the 1  st/nd/rd time
ERROR [2018-04-10 10:36:35] URL:  https://graph.facebook.com/v2.10/YYYYYYYYYYYYYYY/insights?access_token=ZZZZZZZZZZZZ&limit=25&after=NDI0
ERROR [2018-04-10 10:36:35] Method:  GET
ERROR [2018-04-10 10:36:35] Params:  List of 2
 $ limit: chr "25"
 $ after: chr "NDI0"
Fehler in fbad_request(path = url$path, method = "GET", params = url$params) : 
  This is a bug in the fbRads package. Please report on GitHub with a detailed output: Resolving timed out after 3542 milliseconds
Ruft auf: fb_insights ... fb_insights -> fbad_request_next_page -> fbad_request

**Comment by thomiko** [comment]
Two more comments: 
- The script runs once a day, usually without any problems. This year it only failed one more time, about two weeks ago. I don't know anymore what the problem was at that time.
- I just started it manually and it finished without problems. It ran without exactly the same settings (date range, account) as this morning.

So the error above can hardly be reproduced.

**Comment by daroczig** [comment]
This seems to be a temporarily network error: the first two `connection timeout` was handled by `fbRads` by retrying the query again but failed on the last trial with a time-out on resolving. Closing for now, although error msg could be improved, I agree
