### ISSUE TITLE
Lapply fbad_list_campaign() over list of fbacc objects 

### ISSUE THREAD

**Issue by dataders** [daroczig/fbRads#90]
I want to get all entities for multiple accounts that my firm manages.
Any help would be much appreciated!
```
MyAccounts <- list(
    shark_co = "111111111",
    whale_ltd = "22222222",
    narwhal_inc = "102340304")
```
This works without issue
```
MyFbaccs <- lapply(MyAccounts, fbad_init, token = token, version = '2.12')
```
However, I now want get all entities (campaigns, adsets & ads) for each account using the corresponding fbacc objects I just created.

This is how i think i should work, but instead i get this error: `Error in eval(expr, p) : object 'x' not found`
```
MyCampaigns <- lapply(MyFbaccs , function(x) {
    fbad_list_campaign(
        fbacc = x,
        fields = toJSON(c("account_id", "id","name")))
    })
```
This does work but it it seems unnecessary to initialize the account given that I'll be doing at least 3 more similar calls
```
MyCampaigns <- lapply(MyAccounts, function(x) {
    fbad_init(x, token = token, version = '2.12')
    
    fbad_list_campaign(fields = toJSON(c("account_id","id","name")))
    })
```

**Comment by daroczig** [comment]
Thanks for catching this issue, I'm not really passing `fbacc` but using your 2nd approach that's why I totally missed it.
