### ISSUE TITLE
Facebook Business SDK

### ISSUE THREAD

**Issue by daroczig** [daroczig/fbRads#93]
The Marketing API will be deprecated soon: https://developers.facebook.com/blog/post/2018/05/01/facebook-business-sdk/

TODO: decide on how to continue maintaining `fbRads`. Maybe build on `reticulate` and the Python SDK?

**Comment by bjeavons** [comment]
It's not clear to me what the timeframe here is, do you know?

Graph API v2.12 is supported until May 1, 2020 ~so I presume that the Marketing API (and official SDKs) will be available until then~ (ref: https://developers.facebook.com/docs/graph-api/changelog) tho of course unofficial SDKs can switch to v3.0 now. Edit, Marketing API v2.12 is only available till Aug 7, 2018 :/

**Comment by daroczig** [comment]
Yup, my current understanding is that the current versions of the Marketing API will go away in Aug :disappointed:

**Comment by bjeavons** [comment]
@daroczig What do you think about having fbRads implement any changes of v3.0 as a start? I haven't reviewed those fully yet but can help out with at least regards to audiences and insights.

**Comment by daroczig** [comment]
I will work on this next week. The changelog at https://developers.facebook.com/docs/graph-api/changelog/version3.0#mapi suggests that this update is not that huge after all.

**Comment by daroczig** [comment]
Bumped the default API version to v3.0 in #100 -- after checking the FB changelog, this v2.11 -> v3.0 was more of a branding thing (bundling together 4 APIs into an official SDK) and not much actual change in the Marketing API.

**Comment by bjeavons** [comment]
thanks @daroczig!
