### ISSUE TITLE
Issues with authentication

### ISSUE THREAD

**Issue by lucasdedavid** [daroczig/fbRads#94]
Hi. I'm trying to authenticate in FbRads. Created the app and I am the ads account admin. Double checked. Even tough, I'm having some trouble while connecting the API. 

`auth = fbad_init(account, token, version = fb_api_most_recent_version())
`
 `Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  (#273) This Ads API call requires the user to be admin of the ad account. User is not admin on ad account 366056397096228.`

How could I resolve this?

**Comment by lucasdedavid** [comment]
It's important to note that it's a app created by a business, not my personal account. The package is working when I use my personal ads account id to authenticate.

**Comment by daroczig** [comment]
This doesn't seem to be an R package problem, sorry, I cannot help. I'd suggest checking the Graph API Explorer and Acess Token Debugger at https://developers.facebook.com/tools to confirm that your token is all right, and then let's figure out the R implementation problems here.
