### ISSUE TITLE
Different result for same query

### ISSUE THREAD

**Issue by paul7Junior** [daroczig/fbRads#95]
Hi all,

I have notice a strange behavior with the fb_insights function
If I query this:
```
fb_insights(time_range = tr,
                        time_increment = 1,
                        action_breakdowns = c('action_reaction', 'action_type'),
                        fields = toJSON(c('actions')))
```

and this:
```
fb_insights(time_range = tr,
                        time_increment = 1,
                        action_breakdowns = c('action_type', 'action_reaction'),
                        fields = toJSON(c('actions')))
```
(note I have change the order of action_breakdowns parameter, all other things remaining equal)

I do not have he same result: for the first one I only get action_type whereas for the second query I got both of my actions_breakdowns.

I test the same thing (switching the order of the action_breakdowns) with a curl request and I get both of my breakdowns in both case.

Best regards,

Paul

**Comment by daroczig** [comment]
I think that's expected as per https://developers.facebook.com/docs/marketing-api/insights/breakdowns#combiningbreakdowns

> Due to storage constraints, only some permutations of breakdowns are available.
