### ISSUE TITLE
"Insecure Login Blocked" - https-issue?

### ISSUE THREAD

**Issue by devktpx** [daroczig/fbRads#96]
Halfway through following [these ](https://github.com/daroczig/fbRads)instructions, I got this error message:

![error_fbrads](https://user-images.githubusercontent.com/40054269/42625683-a6c4bee8-85c8-11e8-8a64-57c2eedfc95f.PNG)

Do you have the same problem?

**Comment by martijnvv** [comment]
Plus 1 on this question. I'm running into the same issue.
Any ways to resolve this?

**Comment by daroczig** [comment]
Getting a token on localhost via oauth is not that straightforward anymore since SSL is required, but you can generate a token manually as well -- see eg https://developers.facebook.com/docs/marketing-api/access#manually-getting-access-tokens

**Comment by daroczig** [comment]
I've updated the README in #100 with steps on how to generate tokens manually
