### ISSUE TITLE
fbad_init error ( fbad_request)

### ISSUE THREAD

**Issue by bcastane** [daroczig/fbRads#97]
Hi,
I am trying to connect to facebook using fbRads and everything is working fine (getting the token) except when i try to connect itself (using fbad_init). appears an error saying "unkown path components: /act_XXXXXXXXX" and XXXX is the app id.

I installed fbRads directly from github to have the latest version.

Do you know what could be?

`> fbacc <- fbad_init('XXXXXXXXXXXX', tkn, version="3")
TRACE [2018-07-23 15:43:52] Initializing connection to account XXXXXXXXXXXXvia API v3
ERROR [2018-07-23 15:43:53] URL:  https://graph.facebook.com/v3/act_XXXXXXXXXXXX/
ERROR [2018-07-23 15:43:53] Method:  GET
ERROR [2018-07-23 15:43:53] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,end_advertiser,funding_source,spend_cap,timezone_id,users"
ERROR [2018-07-23 15:43:53] Header: {"Access-Control-Allow-Origin":["*"],"x-app-usage":["{\"call_count\":0,\"total_cputime\":0,\"total_time\":0}"],"Strict-Transport-Security":["max-age=15552000; preload"],"x-fb-trace-id":["Dhaz9NRnx7G"],"x-fb-rev":["4129424"],"Content-Type":["application/json; charset=UTF-8"],"facebook-api-version":["v3.0"],"Cache-Control":["no-store"],"Pragma":["no-cache"],"Expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"WWW-Authenticate":["OAuth \"Facebook Platform\" \"invalid_request\" \"Unknown path components: /act_XXXXXXXXXXXX\""],"X-FB-Debug":["gfM2pjjWPtZJ5wDPronWZqiM/PBWXCbk7GRpVXtl85t9u1kxuECA1OxwLocqxdQB3qNCRQMepucR3KDhMFAQcQ=="],"Date":["Mon, 23 Jul 2018 19:43:52 GMT"],"Connection":["keep-alive"],"Content-Length":["134"],"status":["400"],"statusMessage":["Bad Request"]}
ERROR [2018-07-23 15:43:53] Body: {"error":{"message":"Unknown path components: \/act_XXXXXXXXXXXX","type":"OAuthException","code":2500,"fbtrace_id":"Dhaz9NRnx7G"}}
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  Unknown path components: /act_`

**Comment by bcastane** [comment]
The error:

```
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  Unknown path components: /act_XXXXXXXXXXXX
```

**Comment by daroczig** [comment]
I don't have much experience with the new API version, but I think you need to specify `3.0` instead of `3`.

**Comment by bcastane** [comment]
I tried with the 3.0 insted of the 3. 
and now i get that the service temporarily unavailable:

`{
  "error": {
    "message": "(#2) Service temporarily unavailable",
    "type": "OAuthException",
    "is_transient": true,
    "code": 2,
    "fbtrace_id": "BYU4EFXfyGv"
  }
}`
