### ISSUE TITLE
Updating the package to work with FB Marketing API versions >= v2.12 ?

### ISSUE THREAD

**Issue by thomiko** [daroczig/fbRads#99]
I received some notifications from Facebook that from next Tuesday (August 7th) all API calls to the Marketing API < 2.12 will fail. Here is the notification in German:

![facebook api](https://user-images.githubusercontent.com/16490122/43637042-06857e2e-9714-11e8-8e37-801315992421.png)

The latest version of this package only supports calls up to v2.11:

fb_api_most_recent_version()
[1] "2.11"

Do you intend to update the package anytime soon or is there an unofficial workaround to make the package work with Marketing API v2.12 in the meantime?

Thanks!

**Comment by thomiko** [comment]
I just changed the version of the Facebook app to v2.12 and changed this call to the fbad_init method:
fbad_init(accountid = '1234567890', token = tkn, version = '2.12')

It works without any problems. Is the info given by fb_api_most_recent_version() correct?

**Comment by daroczig** [comment]
Yup, `fb_api_most_recent_version` is out of date -- I'll push an update early next week to bump it to `v3.0`. Meanwhile setting the version in `fbad_init` is the suggested way to overcome this issue if you are limited by this.

**Comment by daroczig** [comment]
The default API version was bumped in #100
